/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountdownOverlay: typeof import('./src/components/game/CountdownOverlay.vue')['default']
    GameOverPanel: typeof import('./src/components/game/GameOverPanel.vue')['default']
    LobbyPanel: typeof import('./src/components/game/LobbyPanel.vue')['default']
    QuestionCard: typeof import('./src/components/game/QuestionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreRevealPanel: typeof import('./src/components/game/ScoreRevealPanel.vue')['default']
    TimerRing: typeof import('./src/components/game/TimerRing.vue')['default']
  }
}
