import type { FastifyInstance } from 'fastify'
import { supabaseAdmin } from '../supabase/client.js'

interface QuestionSeed {
  type: string
  difficulty: string
  stem: string
  options: string[]
  correct_index: number
  explanation: string
  time_limit_ms: number
  tags: string[]
}

// ===== WORD BANKS =====
const vocabPairs = {
  easy: [
    ['Happy', 'Joyful', 'Sad', 'Angry', 'Tired'],
    ['Big', 'Large', 'Small', 'Tall', 'Thin'],
    ['Beautiful', 'Pretty', 'Ugly', 'Boring', 'Strange'],
    ['Quick', 'Fast', 'Slow', 'Heavy', 'Quiet'],
    ['Begin', 'Start', 'End', 'Stop', 'Pause'],
    ['Smart', 'Intelligent', 'Foolish', 'Weak', 'Slow'],
    ['Silent', 'Quiet', 'Loud', 'Noisy', 'Busy'],
    ['Wealthy', 'Rich', 'Poor', 'Healthy', 'Sick'],
    ['Ancient', 'Old', 'New', 'Young', 'Modern'],
    ['Courage', 'Bravery', 'Fear', 'Weakness', 'Laziness'],
    ['Furious', 'Very angry', 'Calm', 'Happy', 'Sad'],
    ['Enormous', 'Very large', 'Tiny', 'Normal', 'Strange'],
    ['Delicious', 'Tasty', 'Terrible', 'Bitter', 'Plain'],
    ['Fragile', 'Easily broken', 'Strong', 'Heavy', 'Flexible'],
    ['Patient', 'Able to wait', 'In a hurry', 'Angry', 'Sick'],
    ['Generous', 'Willing to give', 'Selfish', 'Greedy', 'Poor'],
    ['Ordinary', 'Common', 'Special', 'Unusual', 'Rare'],
    ['Polite', 'Respectful', 'Rude', 'Loud', 'Shy'],
    ['Accurate', 'Exact', 'Wrong', 'Approximate', 'False'],
    ['Frequently', 'Often', 'Rarely', 'Never', 'Sometimes'],
    ['Beneath', 'Under', 'Above', 'Beside', 'Beyond'],
    ['Purchase', 'Buy', 'Sell', 'Rent', 'Borrow'],
    ['Assist', 'Help', 'Hinder', 'Ignore', 'Teach'],
    ['Permit', 'Allow', 'Forbid', 'Force', 'Suggest'],
    ['Entire', 'Whole', 'Partial', 'Broken', 'Empty'],
    ['Precious', 'Valuable', 'Cheap', 'Common', 'Useless'],
    ['Brief', 'Short', 'Long', 'Detailed', 'Boring'],
    ['Obtain', 'Get', 'Lose', 'Give', 'Make'],
    ['Vacant', 'Empty', 'Full', 'Busy', 'Crowded'],
    ['Eternal', 'Forever', 'Temporary', 'Brief', 'Recent'],
    ['Neat', 'Tidy', 'Messy', 'Dirty', 'Large'],
    ['Damp', 'Slightly wet', 'Completely dry', 'Very hot', 'Frozen'],
    ['Slender', 'Thin', 'Fat', 'Short', 'Wide'],
    ['Annual', 'Yearly', 'Monthly', 'Weekly', 'Daily'],
    ['Brave', 'Courageous', 'Cowardly', 'Weak', 'Timid'],
    ['Calm', 'Peaceful', 'Angry', 'Excited', 'Nervous'],
    ['Clever', 'Intelligent', 'Stupid', 'Lazy', 'Slow'],
    ['Dull', 'Boring', 'Exciting', 'Sharp', 'Bright'],
    ['Eager', 'Enthusiastic', 'Reluctant', 'Bored', 'Tired'],
    ['Fair', 'Just', 'Unfair', 'Biased', 'Wrong'],
    ['Gentle', 'Mild', 'Rough', 'Harsh', 'Strong'],
    ['Honest', 'Truthful', 'Dishonest', 'Deceitful', 'Mean'],
    ['Ideal', 'Perfect', 'Flawed', 'Bad', 'Wrong'],
    ['Jolly', 'Cheerful', 'Gloomy', 'Sad', 'Angry'],
    ['Keen', 'Eager', 'Apathetic', 'Dull', 'Slow'],
    ['Loyal', 'Faithful', 'Disloyal', 'Unfaithful', 'Hostile'],
    ['Merry', 'Joyful', 'Gloomy', 'Sad', 'Angry'],
    ['Narrow', 'Thin', 'Wide', 'Broad', 'Deep'],
    ['Odd', 'Strange', 'Normal', 'Common', 'Regular'],
    ['Pale', 'Light', 'Dark', 'Bright', 'Deep'],
    ['Rapid', 'Quick', 'Slow', 'Steady', 'Heavy'],
    ['Savage', 'Wild', 'Tame', 'Gentle', 'Mild'],
    ['Tender', 'Soft', 'Tough', 'Hard', 'Rough'],
    ['Urgent', 'Pressing', 'Trivial', 'Minor', 'Optional'],
    ['Vast', 'Immense', 'Tiny', 'Small', 'Limited'],
    ['Wicked', 'Evil', 'Good', 'Kind', 'Nice'],
    ['Yield', 'Produce', 'Consume', 'Destroy', 'Keep'],
    ['Zealous', 'Passionate', 'Apathetic', 'Calm', 'Cold'],
    ['Abrupt', 'Sudden', 'Gradual', 'Slow', 'Steady'],
    ['Bold', 'Daring', 'Timid', 'Shy', 'Weak'],
  ],
  medium: [
    ['Eloquent', 'Fluent and persuasive', 'Quiet and shy', 'Angry and loud', 'Slow and careful'],
    ['Benevolent', 'Kind and generous', 'Cruel and mean', 'Rich and powerful', 'Poor and humble'],
    ['Meticulous', 'Very careful and precise', 'Careless', 'Quick', 'Lazy'],
    ['Abundant', 'Plentiful', 'Scarce', 'Expensive', 'Beautiful'],
    ['Candid', 'Honest and direct', 'Dishonest', 'Secretive', 'Confused'],
    ['Diligent', 'Hardworking', 'Lazy', 'Intelligent', 'Quick'],
    ['Feeble', 'Weak', 'Strong', 'Brave', 'Clever'],
    ['Genuine', 'Real and authentic', 'Fake', 'Expensive', 'Common'],
    ['Hostile', 'Unfriendly and aggressive', 'Friendly', 'Peaceful', 'Shy'],
    ['Immense', 'Extremely large', 'Very small', 'Average sized', 'Very heavy'],
    ['Jubilant', 'Extremely happy', 'Very sad', 'Moderately pleased', 'Calm'],
    ['Keen', 'Eager and enthusiastic', 'Reluctant', 'Bored', 'Confused'],
    ['Lavish', 'Luxurious and extravagant', 'Plain', 'Cheap', 'Simple'],
    ['Modest', 'Humble and unassuming', 'Arrogant', 'Rich', 'Famous'],
    ['Novice', 'Beginner', 'Expert', 'Teacher', 'Professional'],
    ['Optimistic', 'Hopeful about the future', 'Pessimistic', 'Realistic', 'Depressed'],
    ['Persistent', 'Continuing firmly', 'Giving up easily', 'Changing often', 'Delaying always'],
    ['Reluctant', 'Unwilling and hesitant', 'Eager', 'Quick', 'Happy'],
    ['Spontaneous', 'Unplanned and impulsive', 'Careful', 'Planned', 'Deliberate'],
    ['Tedious', 'Boring and repetitive', 'Exciting', 'Quick', 'Important'],
    ['Versatile', 'Able to adapt to many functions', 'Limited', 'Specialized', 'Inflexible'],
    ['Inevitable', 'Certain to happen', 'Avoidable', 'Unlikely', 'Optional'],
    ['Subtle', 'Delicate and understated', 'Obvious', 'Blunt', 'Harsh'],
    ['Vivid', 'Bright and clear', 'Dull', 'Dark', 'Faint'],
    ['Adamant', 'Refusing to be persuaded', 'Flexible', 'Agreeable', 'Uncertain'],
    ['Barren', 'Unable to produce life', 'Fertile', 'Lush', 'Rich'],
    ['Chronic', 'Long-lasting and constant', 'Temporary', 'Acute', 'Brief'],
    ['Defiant', 'Showing resistance', 'Obedient', 'Compliant', 'Submissive'],
    ['Exquisite', 'Extremely beautiful', 'Ugly', 'Plain', 'Ordinary'],
    ['Flawless', 'Without any imperfections', 'Defective', 'Damaged', 'Imperfect'],
    ['Grim', 'Depressing and gloomy', 'Cheerful', 'Bright', 'Optimistic'],
    ['Harsh', 'Cruel and severe', 'Gentle', 'Soft', 'Kind'],
    ['Intricate', 'Very detailed and complicated', 'Simple', 'Plain', 'Basic'],
    ['Lethal', 'Deadly', 'Harmless', 'Safe', 'Benign'],
    ['Meager', 'Not enough, very little', 'Abundant', 'Plentiful', 'Ample'],
    ['Notorious', 'Famous for something bad', 'Unknown', 'Obscure', 'Famous for good'],
    ['Obsolete', 'No longer in use', 'Modern', 'Current', 'New'],
    ['Peculiar', 'Strange or unusual', 'Normal', 'Common', 'Ordinary'],
    ['Resilient', 'Able to recover quickly', 'Fragile', 'Weak', 'Vulnerable'],
    ['Solemn', 'Serious and dignified', 'Cheerful', 'Lighthearted', 'Humorous'],
    ['Tranquil', 'Calm and peaceful', 'Chaotic', 'Turbulent', 'Noisy'],
    ['Vulnerable', 'Easily harmed', 'Protected', 'Safe', 'Secure'],
    ['Weary', 'Very tired', 'Energetic', 'Refreshed', 'Active'],
    ['Zealous', 'Having great energy/enthusiasm', 'Apathetic', 'Indifferent', 'Lazy'],
    ['Ambiguous', 'Open to multiple interpretations', 'Clear', 'Unambiguous', 'Definite'],
  ],
  hard: [
    ['Ephemeral', 'Lasting a very short time', 'Eternal', 'Permanent', 'Changing slowly'],
    ['Ubiquitous', 'Found everywhere', 'Very rare', 'Hidden', 'Unique'],
    ['Pragmatic', 'Practical and realistic', 'Idealistic', 'Theoretical', 'Emotional'],
    ['Sycophant', 'A flatterer seeking favor', 'An honest critic', 'A loyal friend', 'A brave leader'],
    ['Pernicious', 'Having a harmful effect', 'Beneficial', 'Neutral', 'Temporary'],
    ['Ameliorate', 'To make better', 'Make worse', 'Ignore', 'Destroy'],
    ['Loquacious', 'Very talkative', 'Quiet', 'Angry', 'Shy'],
    ['Obsequious', 'Excessively obedient', 'Rebellious', 'Independent', 'Proud'],
    ['Taciturn', 'Reserved and uncommunicative', 'Talkative', 'Friendly', 'Angry'],
    ['Magnanimous', 'Very generous and forgiving', 'Petty and mean', 'Rich and famous', 'Quiet and shy'],
    ['Recalcitrant', 'Stubbornly uncooperative', 'Cooperative', 'Enthusiastic', 'Intelligent'],
    ['Perspicacious', 'Having keen insight', 'Confused', 'Slow to understand', 'Forgetful'],
    ['Obstreperous', 'Noisy and difficult to control', 'Quiet and calm', 'Happy and content', 'Weak and fragile'],
    ['Pusillanimous', 'Cowardly and timid', 'Brave', 'Bold', 'Strong'],
    ['Vicissitude', 'A change of circumstances', 'Stability', 'A type of food', 'A celebration'],
    ['Acrimonious', 'Bitter and angry', 'Harmonious', 'Peaceful', 'Sweet'],
    ['Bombastic', 'Pompous and pretentious', 'Humble', 'Simple', 'Quiet'],
    ['Capitulate', 'To surrender', 'Fight', 'Resist', 'Attack'],
    ['Deleterious', 'Harmful', 'Beneficial', 'Helpful', 'Advantageous'],
    ['Egregious', 'Shockingly bad', 'Excellent', 'Average', 'Normal'],
    ['Fastidious', 'Very attentive to detail', 'Careless', 'Sloppy', 'Negligent'],
    ['Grandiose', 'Impressive but impractical', 'Modest', 'Simple', 'Practical'],
    ['Iconoclast', 'One who challenges beliefs', 'Traditionalist', 'Follower', 'Conformist'],
    ['Juxtapose', 'Place side by side for comparison', 'Separate', 'Remove', 'Hide'],
    ['Kowtow', 'Act in a submissive way', 'Defy', 'Challenge', 'Dominate'],
    ['Lugubrious', 'Looking sad and dismal', 'Cheerful', 'Bright', 'Joyful'],
    ['Mendacious', 'Not telling the truth', 'Honest', 'Truthful', 'Sincere'],
    ['Nefarious', 'Wicked and criminal', 'Virtuous', 'Good', 'Moral'],
    ['Obfuscate', 'Make unclear or confusing', 'Clarify', 'Explain', 'Simplify'],
    ['Parsimonious', 'Unwilling to spend money', 'Generous', 'Lavish', 'Extravagant'],
    ['Querulous', 'Complaining in a whiny way', 'Content', 'Satisfied', 'Happy'],
    ['Recrudescence', 'Revival of something bad', 'Decline', 'End', 'Cessation'],
    ['Sagacious', 'Having good judgment', 'Foolish', 'Unwise', 'Stupid'],
    ['Trepidation', 'Feeling of fear or anxiety', 'Calm', 'Confidence', 'Peace'],
    ['Unctuous', 'Excessively flattering', 'Genuine', 'Sincere', 'Real'],
    ['Vitriolic', 'Filled with bitter criticism', 'Kind', 'Gentle', 'Praising'],
    ['Xenophobia', 'Fear of foreigners', 'Openness', 'Welcoming', 'Tolerance'],
    ['Yokel', 'An unsophisticated country person', 'Sophisticate', 'Urbanite', 'Cosmopolitan'],
    ['Anathema', 'Something greatly hated', 'Something beloved', 'Something average', 'Something boring'],
    ['Bellicose', 'Demonstrating aggression', 'Peaceful', 'Calm', 'Gentle'],
    ['Cacophony', 'Harsh mixture of sounds', 'Harmony', 'Melody', 'Silence'],
    ['Diffident', 'Modest and shy', 'Confident', 'Bold', 'Assertive'],
    ['Enervate', 'Cause to feel drained', 'Energize', 'Invigorate', 'Strengthen'],
    ['Fractious', 'Irritable and quarrelsome', 'Agreeable', 'Cooperative', 'Calm'],
    ['Garrulous', 'Excessively talkative', 'Taciturn', 'Quiet', 'Reticent'],
    ['Hubris', 'Excessive pride', 'Humility', 'Modesty', 'Meekness'],
    ['Insidious', 'Proceeding harmfully but subtly', 'Direct', 'Obvious', 'Harmless'],
    ['Laconic', 'Using very few words', 'Verbose', 'Talkative', 'Long-winded'],
    ['Mercurial', 'Subject to sudden changes', 'Stable', 'Constant', 'Steady'],
    ['Pugnacious', 'Eager to argue or fight', 'Peaceable', 'Friendly', 'Agreeable'],
  ],
}

const synonymPairs: [string, string, string][] = [
  ['Happy', 'Glad', 'Sad'], ['Fast', 'Quick', 'Slow'], ['Angry', 'Mad', 'Calm'],
  ['Pretty', 'Beautiful', 'Ugly'], ['Smart', 'Clever', 'Foolish'],
  ['Brave', 'Courageous', 'Cowardly'], ['Tiny', 'Small', 'Large'],
  ['Wealthy', 'Rich', 'Poor'], ['Begin', 'Start', 'End'],
  ['Assist', 'Help', 'Hinder'], ['Calm', 'Peaceful', 'Angry'],
  ['Correct', 'Right', 'Wrong'], ['Quiet', 'Silent', 'Loud'],
  ['Strong', 'Powerful', 'Weak'], ['Sad', 'Unhappy', 'Joyful'],
  ['Tired', 'Exhausted', 'Energetic'], ['Love', 'Adore', 'Hate'],
  ['Big', 'Large', 'Small'], ['Old', 'Ancient', 'New'],
  ['Clean', 'Tidy', 'Dirty'], ['Brave', 'Bold', 'Timid'],
  ['Clever', 'Wise', 'Stupid'], ['Cruel', 'Mean', 'Kind'],
  ['Dangerous', 'Risky', 'Safe'], ['Eager', 'Keen', 'Reluctant'],
  ['False', 'Fake', 'Real'], ['Famous', 'Renowned', 'Unknown'],
  ['Gentle', 'Tender', 'Rough'], ['Hollow', 'Empty', 'Solid'],
  ['Innocent', 'Blameless', 'Guilty'], ['Lazy', 'Idle', 'Active'],
  ['Mad', 'Insane', 'Sane'], ['Polite', 'Courteous', 'Rude'],
  ['Rare', 'Uncommon', 'Common'], ['Shallow', 'Superficial', 'Deep'],
  ['Ugly', 'Unattractive', 'Beautiful'], ['Wicked', 'Evil', 'Good'],
  ['Benevolent', 'Charitable', 'Greedy'], ['Meticulous', 'Thorough', 'Careless'],
  ['Eloquent', 'Articulate', 'Inarticulate'], ['Hostile', 'Antagonistic', 'Friendly'],
  ['Abundant', 'Copious', 'Scarce'], ['Candid', 'Frank', 'Dishonest'],
  ['Diligent', 'Industrious', 'Lazy'], ['Feeble', 'Frail', 'Strong'],
  ['Genuine', 'Authentic', 'Fake'], ['Immense', 'Vast', 'Tiny'],
  ['Jubilant', 'Elated', 'Depressed'], ['Lavish', 'Sumptuous', 'Frugal'],
  ['Modest', 'Humble', 'Arrogant'], ['Novice', 'Beginner', 'Veteran'],
  ['Optimistic', 'Hopeful', 'Pessimistic'], ['Persistent', 'Tenacious', 'Quitter'],
  ['Reluctant', 'Hesitant', 'Eager'], ['Spontaneous', 'Impulsive', 'Planned'],
]

const grammarPatterns = {
  easy: [
    { stem: 'I ___ a student.', answer: 'am', wrong: ['is', 'are', 'be'] },
    { stem: 'She ___ to school every day.', answer: 'goes', wrong: ['go', 'going', 'gone'] },
    { stem: 'They ___ playing football now.', answer: 'are', wrong: ['is', 'am', 'be'] },
    { stem: 'He ___ breakfast this morning.', answer: 'ate', wrong: ['eat', 'eats', 'eating'] },
    { stem: '___ you like coffee?', answer: 'Do', wrong: ['Does', 'Is', 'Are'] },
    { stem: 'There ___ many books on the desk.', answer: 'are', wrong: ['is', 'am', 'be'] },
    { stem: 'I have ___ finished my homework.', answer: 'already', wrong: ['yet', 'since', 'for'] },
    { stem: 'She is ___ than her sister.', answer: 'taller', wrong: ['tall', 'tallest', 'more tall'] },
    { stem: 'We ___ to the park yesterday.', answer: 'went', wrong: ['go', 'gone', 'going'] },
    { stem: 'He can ___ English very well.', answer: 'speak', wrong: ['speaks', 'spoke', 'spoken'] },
    { stem: 'I ___ TV when she called.', answer: 'was watching', wrong: ['watched', 'watch', 'have watched'] },
    { stem: 'She ___ never been to Beijing.', answer: 'has', wrong: ['have', 'is', 'was'] },
    { stem: 'It is ___ interesting book.', answer: 'an', wrong: ['a', 'the', 'no article'] },
    { stem: 'Would you like ___ tea?', answer: 'some', wrong: ['any', 'a', 'an'] },
    { stem: 'How ___ does it cost?', answer: 'much', wrong: ['many', 'long', 'far'] },
    { stem: 'I look forward to ___ you.', answer: 'seeing', wrong: ['see', 'seen', 'saw'] },
    { stem: 'The meeting ___ at 3 PM.', answer: 'starts', wrong: ['start', 'starting', 'started'] },
    { stem: 'If it ___, we will stay home.', answer: 'rains', wrong: ['rain', 'rained', 'raining'] },
    { stem: 'She asked me ___ I was okay.', answer: 'if', wrong: ['that', 'what', 'which'] },
    { stem: '___ book is on the table?', answer: 'Whose', wrong: ['Who', 'Whom', 'Which'] },
    { stem: 'Neither he nor I ___ there.', answer: 'am', wrong: ['is', 'are', 'be'] },
    { stem: 'I wish I ___ a bird.', answer: 'were', wrong: ['am', 'was', 'be'] },
    { stem: 'He ___ to work before 8 AM.', answer: 'goes', wrong: ['go', 'going', 'went'] },
    { stem: 'We ___ lunch right now.', answer: 'are having', wrong: ['have', 'has', 'had'] },
    { stem: 'She ___ her homework already.', answer: 'has done', wrong: ['did', 'does', 'doing'] },
    { stem: 'They ___ to Paris next week.', answer: 'will go', wrong: ['go', 'went', 'going'] },
    { stem: 'The kids ___ in the garden now.', answer: 'are playing', wrong: ['play', 'plays', 'played'] },
    { stem: 'I ___ my keys. Help me find them!', answer: 'have lost', wrong: ['lose', 'lost', 'am losing'] },
    { stem: 'He ___ when I saw him.', answer: 'was sleeping', wrong: ['sleeps', 'slept', 'is sleeping'] },
    { stem: 'She ___ English for 5 years.', answer: 'has studied', wrong: ['studies', 'studied', 'studying'] },
    { stem: '___ sun rises in the east.', answer: 'The', wrong: ['A', 'An', 'No article'] },
    { stem: 'He is ___ honest man.', answer: 'an', wrong: ['a', 'the', 'no article'] },
    { stem: 'She lives ___ London.', answer: 'in', wrong: ['at', 'on', 'to'] },
    { stem: 'See you ___ Monday!', answer: 'on', wrong: ['in', 'at', 'to'] },
    { stem: 'He arrived ___ the airport late.', answer: 'at', wrong: ['in', 'on', 'to'] },
    { stem: 'I am good ___ math.', answer: 'at', wrong: ['in', 'on', 'for'] },
    { stem: 'She is afraid ___ spiders.', answer: 'of', wrong: ['for', 'in', 'with'] },
    { stem: 'This book belongs ___ me.', answer: 'to', wrong: ['for', 'with', 'of'] },
    { stem: 'We agreed ___ the plan.', answer: 'to', wrong: ['with', 'for', 'on'] },
    { stem: 'She takes care ___ her mother.', answer: 'of', wrong: ['for', 'with', 'to'] },
  ],
  medium: [
    { stem: 'Had I known, I ___ come earlier.', answer: 'would have', wrong: ['will have', 'had', 'have'] },
    { stem: 'It is high time we ___ action.', answer: 'took', wrong: ['take', 'taken', 'taking'] },
    { stem: 'Seldom ___ such a beautiful sight.', answer: 'have I seen', wrong: ['I have seen', 'I saw', 'did I saw'] },
    { stem: 'The more you practice, ___ you become.', answer: 'the better', wrong: ['better', 'the best', 'more better'] },
    { stem: 'I would rather you ___ here tomorrow.', answer: 'came', wrong: ['come', 'coming', 'will come'] },
    { stem: '___ the weather, the event was a success.', answer: 'Despite', wrong: ['Although', 'Because of', 'However'] },
    { stem: 'Not until she spoke ___ realize she was English.', answer: 'did I', wrong: ['I did', 'I had', 'had I'] },
    { stem: 'The house needs ___.', answer: 'painting', wrong: ['to paint', 'painted', 'paint'] },
    { stem: 'It is essential that he ___ on time.', answer: 'be', wrong: ['is', 'was', 'will be'] },
    { stem: 'No sooner had he arrived ___ it started raining.', answer: 'than', wrong: ['when', 'then', 'that'] },
    { stem: 'He denied ___ the money.', answer: 'having stolen', wrong: ['to steal', 'steal', 'stole'] },
    { stem: 'But for your help, I ___ the exam.', answer: 'would have failed', wrong: ['will fail', 'failed', 'had failed'] },
    { stem: 'She insisted that he ___ present.', answer: 'be', wrong: ['is', 'was', 'being'] },
    { stem: '___ as it may seem, it is true.', answer: 'Strange', wrong: ['Strangely', 'More strange', 'The strangest'] },
    { stem: 'He is second to ___ in mathematics.', answer: 'none', wrong: ['anyone', 'nobody', 'someone'] },
    { stem: 'I regret ___ you that your application was denied.', answer: 'to inform', wrong: ['informing', 'inform', 'informed'] },
    { stem: 'She suggested that we ___ early.', answer: 'leave', wrong: ['left', 'leaving', 'would leave'] },
    { stem: 'So fast ___ that nobody could catch him.', answer: 'did he run', wrong: ['he ran', 'ran he', 'he did run'] },
    { stem: 'By next year, I ___ here for 10 years.', answer: 'will have worked', wrong: ['will work', 'worked', 'have worked'] },
    { stem: 'I ___ to the party if I had been invited.', answer: 'would have gone', wrong: ['will go', 'went', 'would go'] },
    { stem: 'Neither the teacher nor the students ___ happy.', answer: 'were', wrong: ['was', 'is', 'has been'] },
    { stem: 'Each of the books ___ a different cover.', answer: 'has', wrong: ['have', 'are having', 'having'] },
    { stem: 'The number of students ___ increasing.', answer: 'is', wrong: ['are', 'were', 'have been'] },
    { stem: 'A number of students ___ absent today.', answer: 'are', wrong: ['is', 'was', 'has been'] },
    { stem: 'I object to ___ treated like a child.', answer: 'being', wrong: ['be', 'been', 'is'] },
    { stem: 'He is used to ___ up early.', answer: 'getting', wrong: ['get', 'got', 'gotten'] },
    { stem: 'She is looking forward to ___ you.', answer: 'meeting', wrong: ['meet', 'met', 'meets'] },
    { stem: 'I can\'t help ___ at his jokes.', answer: 'laughing', wrong: ['laugh', 'laughed', 'to laugh'] },
    { stem: 'It is no use ___ over spilt milk.', answer: 'crying', wrong: ['cry', 'cried', 'to cry'] },
    { stem: '___ rich is not the same as being happy.', answer: 'Being', wrong: ['To be', 'Be', 'Been'] },
  ],
  hard: [
    { stem: 'Were it not for his help, I ___ now.', answer: 'would not be here', wrong: ['am not here', 'was not here', 'will not be'] },
    { stem: 'The subjunctive mood requires that every student ___ the assignment.', answer: 'submit', wrong: ['submits', 'submitted', 'will submit'] },
    { stem: 'Scarcely ___ the room when the phone rang.', answer: 'had I entered', wrong: ['I had entered', 'I entered', 'entered I'] },
    { stem: 'To ___ should I address this letter?', answer: 'whom', wrong: ['who', 'which', 'whose'] },
    { stem: 'The data ___ been analyzed thoroughly.', answer: 'have', wrong: ['has', 'is', 'was'] },
    { stem: 'Under no circumstances ___ be late.', answer: 'should you', wrong: ['you should', 'you would', 'will you'] },
    { stem: 'I appreciate ___ given this opportunity.', answer: 'having been', wrong: ['to be', 'being', 'to have been'] },
    { stem: 'Each of the participants ___ a certificate.', answer: 'receives', wrong: ['receive', 'receiving', 'have received'] },
    { stem: 'The committee ___ divided in their opinions.', answer: 'are', wrong: ['is', 'was', 'has been'] },
    { stem: 'It was not until the 19th century that women ___ the right to vote.', answer: 'gained', wrong: ['gain', 'had gained', 'have gained'] },
    { stem: 'I wish I ___ harder for the exam last week.', answer: 'had studied', wrong: ['studied', 'study', 'have studied'] },
    { stem: 'Would that I ___ there to see it!', answer: 'had been', wrong: ['was', 'am', 'were'] },
    { stem: 'It is imperative that he ___ immediately.', answer: 'leave', wrong: ['leaves', 'left', 'will leave'] },
    { stem: 'If only she ___ me the truth earlier.', answer: 'had told', wrong: ['told', 'tells', 'would tell'] },
    { stem: 'So beautiful ___ that everyone stared.', answer: 'was she', wrong: ['she was', 'did she', 'she did'] },
    { stem: 'Not a single word ___ spoken.', answer: 'was', wrong: ['were', 'has', 'have'] },
    { stem: 'Rarely ___ such dedication in one so young.', answer: 'does one see', wrong: ['one sees', 'one does see', 'sees one'] },
    { stem: 'The poor ___ always with us.', answer: 'are', wrong: ['is', 'was', 'has been'] },
    { stem: 'Ten miles ___ a long distance to walk.', answer: 'is', wrong: ['are', 'were', 'have been'] },
    { stem: 'Many a student ___ made this mistake.', answer: 'has', wrong: ['have', 'are', 'were'] },
    { stem: 'It is I who ___ responsible.', answer: 'am', wrong: ['is', 'are', 'were'] },
    { stem: 'Not only the car but also the bicycles ___ damaged.', answer: 'were', wrong: ['was', 'is', 'has been'] },
    { stem: 'Twice as many people ___ at the event as expected.', answer: 'were', wrong: ['was', 'is', 'has been'] },
    { stem: 'One third of the population ___ illiterate.', answer: 'is', wrong: ['are', 'were', 'have been'] },
    { stem: 'Bread and butter ___ his only food.', answer: 'is', wrong: ['are', 'were', 'have been'] },
  ],
}

// Reading passages
const readingPassages = {
  easy: [
    {
      passage: 'Tom has a dog named Max. Every morning, Tom takes Max for a walk in the park. Max loves to chase birds.',
      question: 'What does Tom do every morning?',
      answer: 'Walk his dog', wrong: ['Feed his cat', 'Go to school', 'Read a book'],
    },
    {
      passage: 'Lucy is a teacher. She works at a primary school. She teaches math to young children. She loves her job.',
      question: "What is Lucy's job?",
      answer: 'Teacher', wrong: ['Doctor', 'Lawyer', 'Nurse'],
    },
    {
      passage: 'It was raining heavily. John forgot his umbrella. He got very wet on his way to work.',
      question: 'Why did John get wet?',
      answer: 'He forgot his umbrella', wrong: ['He liked rain', 'He went swimming', 'His umbrella was broken'],
    },
    {
      passage: 'Sarah bought apples, bananas, and oranges at the store. She paid $20 and got $5 change.',
      question: 'How much did she spend?',
      answer: '$15', wrong: ['$20', '$25', '$5'],
    },
    {
      passage: 'Peter likes to play basketball after school. He practices every day. His dream is to become a professional player.',
      question: "What is Peter's dream?",
      answer: 'To become a professional basketball player', wrong: ['To become a teacher', 'To go to college', 'To stop playing basketball'],
    },
    {
      passage: 'Emily cooked dinner for her family. She made spaghetti, salad, and garlic bread. Everyone enjoyed the meal.',
      question: 'What did Emily NOT make?',
      answer: 'Pizza', wrong: ['Spaghetti', 'Salad', 'Garlic bread'],
    },
    {
      passage: 'The movie started at 7:00 PM and ended at 9:15 PM.',
      question: 'How long was the movie?',
      answer: '2 hours 15 minutes', wrong: ['2 hours', '1 hour 45 minutes', '2 hours 30 minutes'],
    },
    {
      passage: 'David is saving money for a new bicycle. The bicycle costs $240. He saves $30 each week.',
      question: 'How many weeks will it take?',
      answer: '8 weeks', wrong: ['6 weeks', '10 weeks', '12 weeks'],
    },
    {
      passage: 'Anna has three children: two boys and one girl. Her oldest child is 10 and her youngest is 4.',
      question: 'How many children does Anna have?',
      answer: '3', wrong: ['2', '4', '5'],
    },
    {
      passage: 'The library is closed on Sundays. It opens at 9 AM on weekdays and 10 AM on Saturdays.',
      question: 'When does the library open on Wednesday?',
      answer: '9 AM', wrong: ['10 AM', '8 AM', 'It is closed'],
    },
    {
      passage: 'Mike loves animals. He has two cats, a dog, and a parrot. His favorite is the parrot because it can talk.',
      question: "What is Mike's favorite pet?",
      answer: 'The parrot', wrong: ['The dog', 'The cats', 'None of them'],
    },
    {
      passage: 'Lisa went to the supermarket. She needed milk, eggs, and bread. The milk cost $3, eggs cost $4, and bread cost $2.',
      question: 'How much did Lisa spend in total?',
      answer: '$9', wrong: ['$7', '$8', '$10'],
    },
    {
      passage: 'Jack gets up at 7:00 AM every day. He eats breakfast at 7:30 and leaves home at 8:00. School starts at 8:30.',
      question: 'What time does Jack leave home?',
      answer: '8:00 AM', wrong: ['7:00 AM', '7:30 AM', '8:30 AM'],
    },
    {
      passage: 'The weather forecast says it will be sunny tomorrow with a high of 28 degrees. Perfect weather for a picnic!',
      question: 'What is the weather prediction for tomorrow?',
      answer: 'Sunny and warm', wrong: ['Rainy', 'Snowy', 'Cloudy and cold'],
    },
    {
      passage: 'Amy is learning to play the piano. She practices for 30 minutes every day. She has been learning for 6 months.',
      question: 'How long has Amy been learning piano?',
      answer: '6 months', wrong: ['30 days', '6 weeks', '1 year'],
    },
  ],
  medium: [
    {
      passage: 'Climate change is causing sea levels to rise. Scientists predict that many coastal cities could face flooding problems by 2050. Governments are working on plans to reduce carbon emissions.',
      question: 'What is the main concern in this passage?',
      answer: 'Rising sea levels threatening coastal cities', wrong: ['More rain in cities', 'Too many people living near the sea', 'Carbon emissions increasing without any plan'],
    },
    {
      passage: 'The Industrial Revolution began in Britain in the late 18th century. It transformed manufacturing from hand production to machine production. This led to urbanization as people moved to cities for factory jobs.',
      question: 'What was a key effect of the Industrial Revolution?',
      answer: 'People moved to cities', wrong: ['People returned to farms', 'Manufacturing decreased', 'Machines became less important'],
    },
    {
      passage: 'Studies show that regular exercise improves mental health. Physical activity releases endorphins that reduce stress and anxiety. Even 30 minutes of walking daily can make a significant difference.',
      question: 'What benefit of exercise is mentioned?',
      answer: 'It reduces stress', wrong: ['It makes you stronger', 'It helps you lose weight', 'It improves sleep only'],
    },
    {
      passage: 'The Great Wall of China stretches over 13,000 miles. It was built over many centuries by different dynasties. Originally constructed for defense, it is now a UNESCO World Heritage site.',
      question: 'What was the original purpose of the Great Wall?',
      answer: 'Military defense', wrong: ['Tourism', 'Trade route', 'Religious worship'],
    },
    {
      passage: 'Renewable energy sources like solar and wind are becoming cheaper than fossil fuels. Many countries are investing in green energy to meet climate goals. The transition could create millions of new jobs.',
      question: 'What is driving the growth of renewable energy?',
      answer: 'Lower costs and climate concerns', wrong: ['Government mandates only', 'Fossil fuel shortages', 'Public protests only'],
    },
    {
      passage: 'In Japan, the tea ceremony is an important cultural tradition. It emphasizes harmony, respect, purity, and tranquility. The ceremony can last several hours and requires years of training to master.',
      question: 'What value is NOT mentioned as part of the tea ceremony?',
      answer: 'Wealth', wrong: ['Harmony', 'Respect', 'Purity'],
    },
    {
      passage: 'Shakespeare wrote 37 plays during his lifetime, including comedies, tragedies, and histories. His works have been translated into every major language. He is widely considered the greatest writer in the English language.',
      question: 'How many plays did Shakespeare write?',
      answer: '37', wrong: ['27', '47', '57'],
    },
    {
      passage: 'The human brain contains approximately 86 billion neurons. Each neuron can connect to thousands of others. These connections, called synapses, allow us to think, learn, and remember.',
      question: 'What enables learning and memory in the brain?',
      answer: 'Connections between neurons called synapses', wrong: ['The size of the brain', 'The number of brain cells only', 'Blood flow to the brain'],
    },
    {
      passage: 'Marie Curie was the first woman to win a Nobel Prize. She discovered the elements polonium and radium. Her work in radioactivity paved the way for modern cancer treatments.',
      question: 'What did Marie Curie discover?',
      answer: 'Polonium and radium', wrong: ['Penicillin', 'Electricity', 'X-rays'],
    },
    {
      passage: 'The Silk Road was a network of trade routes connecting East and West. It was central to economic and cultural interactions for over 1,500 years. Goods like silk, spices, and precious stones were traded.',
      question: 'What was the main purpose of the Silk Road?',
      answer: 'Trade between East and West', wrong: ['Military conquest', 'Religious pilgrimage only', 'Migration of people only'],
    },
    {
      passage: 'Photosynthesis is the process by which plants convert sunlight into energy. It requires water, carbon dioxide, and sunlight. Oxygen is released as a byproduct.',
      question: 'What gas do plants release during photosynthesis?',
      answer: 'Oxygen', wrong: ['Carbon dioxide', 'Nitrogen', 'Hydrogen'],
    },
    {
      passage: 'Vincent van Gogh only sold one painting during his lifetime. Today, his works are among the most expensive ever sold. His painting "Starry Night" is one of the most recognized artworks in the world.',
      question: 'How many paintings did van Gogh sell while alive?',
      answer: 'One', wrong: ['None', 'Ten', 'Over a hundred'],
    },
    {
      passage: 'Penguins cannot fly, but they are excellent swimmers. They spend up to 75% of their lives in water. Emperor penguins can dive to depths of over 500 meters.',
      question: 'What can Emperor penguins do?',
      answer: 'Dive over 500 meters deep', wrong: ['Fly at great heights', 'Run very fast', 'Live in hot climates'],
    },
    {
      passage: 'The Eiffel Tower was built for the 1889 Worlds Fair. It was supposed to be torn down after 20 years. It was saved because it proved useful as a radio transmission tower.',
      question: 'Why was the Eiffel Tower saved from demolition?',
      answer: 'It was useful as a radio tower', wrong: ['Tourists complained', 'It became a symbol', 'The government changed plans'],
    },
    {
      passage: 'Diamonds are formed deep within the Earth under extreme pressure and heat. They are brought to the surface by volcanic eruptions. The largest diamond ever found weighed over 3,100 carats.',
      question: 'How are diamonds brought to the surface?',
      answer: 'By volcanic eruptions', wrong: ['By miners digging', 'By earthquakes', 'By water erosion'],
    },
  ],
  hard: [
    {
      passage: 'Quantum computing leverages quantum mechanical phenomena such as superposition and entanglement to perform computation. Unlike classical bits, quantum bits (qubits) can exist in multiple states simultaneously, theoretically allowing exponential speedups for certain problems.',
      question: 'What gives quantum computers their computational advantage?',
      answer: 'Qubits can exist in multiple states simultaneously', wrong: ['They use more electricity', 'They are physically larger', 'They have more memory'],
    },
    {
      passage: 'Keynesian economics posits that during recessions, government should increase spending to stimulate demand. This contradicts classical economic theory, which advocates for market self-correction. The debate continues to influence modern fiscal policy.',
      question: 'What does Keynesian economics recommend during recessions?',
      answer: 'Increasing government spending', wrong: ['Reducing government spending', 'Letting the market self-correct', 'Raising interest rates immediately'],
    },
    {
      passage: 'CRISPR-Cas9 is a revolutionary gene-editing technology adapted from a natural bacterial defense mechanism. It allows scientists to make precise modifications to DNA sequences, offering potential for treating genetic diseases while raising ethical concerns.',
      question: 'What is the source of the CRISPR-Cas9 technology?',
      answer: 'It was adapted from a bacterial defense system', wrong: ['It was invented entirely in a laboratory', 'It was discovered in plant cells', 'It was developed by computer algorithms'],
    },
    {
      passage: 'The concept of hedonic adaptation suggests that people quickly return to a relatively stable level of happiness despite major positive or negative life events. Studies on lottery winners and accident victims confirm this phenomenon.',
      question: 'What does hedonic adaptation imply about happiness?',
      answer: 'Major life events do not permanently change our happiness level', wrong: ['Money makes people permanently happier', 'Happiness is determined entirely by genetics', 'Negative events make people permanently sadder'],
    },
    {
      passage: 'The Sapir-Whorf hypothesis proposes that language structure influences worldview and cognitive processes. While the strong version has been largely discredited, the weaker version receives empirical support from studies on color perception and spatial reasoning.',
      question: 'What is the current consensus on the Sapir-Whorf hypothesis?',
      answer: 'The weak version has empirical support', wrong: ['The strong version is widely accepted', 'All versions have been disproven', 'Language has no effect on cognition'],
    },
    {
      passage: 'Game theory analyzes strategic interactions between rational decision-makers. The Nash equilibrium, named after mathematician John Nash, describes a state where no player can benefit by changing only their own strategy.',
      question: 'What is a Nash equilibrium?',
      answer: 'A state where no player benefits from changing only their own strategy', wrong: ['The best strategy for all players', 'A game with no winners', 'A cooperative strategy only'],
    },
    {
      passage: 'Dark matter makes up about 85% of all matter in the universe. It does not emit, absorb, or reflect light, making it invisible. Its existence is inferred from gravitational effects on visible matter.',
      question: 'How do scientists know dark matter exists?',
      answer: 'Through its gravitational effects on visible matter', wrong: ['By directly observing it', 'Through X-ray detection', 'By measuring its temperature'],
    },
    {
      passage: 'The placebo effect demonstrates that belief in a treatment can produce real physiological changes. Studies show that placebos can trigger the release of endorphins, the body\'s natural painkillers, even when patients know they are taking a placebo.',
      question: 'What does the placebo effect demonstrate?',
      answer: 'Belief can produce real physiological changes', wrong: ['Medicine is unnecessary', 'All treatments are psychological', 'Endorphins are ineffective'],
    },
    {
      passage: 'The tragedy of the commons describes a situation where individuals acting rationally in their own self-interest ultimately deplete a shared resource, contrary to the collective good. Classic examples include overfishing, deforestation, and air pollution.',
      question: 'What is the tragedy of the commons?',
      answer: 'Individuals depleting shared resources by acting selfishly', wrong: ['Government mismanagement of public lands', 'Natural disasters affecting communities', 'Private ownership of public spaces'],
    },
    {
      passage: 'Occam\'s razor is a philosophical principle stating that the simplest explanation is usually the best one. In science, it guides researchers to prefer hypotheses with fewer assumptions when multiple theories explain the same data equally well.',
      question: 'What does Occam\'s razor recommend in scientific inquiry?',
      answer: 'Prefer the hypothesis with fewer assumptions', wrong: ['Always choose the newest theory', 'Reject all simple explanations', 'Accept the most complex hypothesis'],
    },
    {
      passage: 'The Streisand effect is a social phenomenon where attempting to hide or censor information has the unintended consequence of publicizing it more widely. It is named after Barbra Streisand, whose attempt to suppress photos of her home drew massive attention.',
      question: 'What causes the Streisand effect?',
      answer: 'Attempting to censor information draws more attention to it', wrong: ['Photos going viral naturally', 'Celebrity endorsements', 'Media bias in reporting'],
    },
    {
      passage: 'Stoicism is an ancient Greek philosophy that teaches emotional resilience through rational thinking. Stoics believe we cannot control external events, only our responses to them. This philosophy has influenced modern cognitive behavioral therapy.',
      question: 'What do Stoics believe we can control?',
      answer: 'Only our responses to events', wrong: ['External events', 'Other people\'s actions', 'Everything in life'],
    },
    {
      passage: 'The Dunning-Kruger effect is a cognitive bias where people with low ability at a task overestimate their ability. Conversely, highly competent individuals tend to underestimate their relative competence, erroneously assuming tasks are easy for others too.',
      question: 'What is the Dunning-Kruger effect?',
      answer: 'Unskilled people overestimate their abilities', wrong: ['Experts always know their limits', 'People learn faster than they think', 'Intelligence cannot be measured'],
    },
    {
      passage: 'Quantum entanglement is a phenomenon where two particles become correlated in such a way that the quantum state of each cannot be described independently. Einstein called it "spooky action at a distance," yet experiments have confirmed its reality.',
      question: 'What did Einstein call quantum entanglement?',
      answer: 'Spooky action at a distance', wrong: ['A beautiful theory', 'The God particle', 'Quantum confusion'],
    },
    {
      passage: 'The prisoner\'s dilemma is a thought experiment in game theory where two rational individuals might not cooperate, even if cooperation benefits both. It illustrates why cooperation is difficult to maintain, even when mutually beneficial.',
      question: 'What does the prisoner\'s dilemma illustrate?',
      answer: 'Why cooperation is difficult even when beneficial', wrong: ['Why prisoners always cooperate', 'How to escape from prison', 'Why selfishness always wins'],
    },
  ],
}

// Translation pairs
const translations = {
  easy: [
    ['"苹果" in English:', 'Apple', 'Orange', 'Banana', 'Grape'],
    ['"书" in English:', 'Book', 'Pen', 'Paper', 'Desk'],
    ['"猫" in English:', 'Cat', 'Dog', 'Bird', 'Fish'],
    ['"水" in English:', 'Water', 'Fire', 'Air', 'Earth'],
    ['"朋友" in English:', 'Friend', 'Family', 'Enemy', 'Teacher'],
    ['"学校" in English:', 'School', 'Hospital', 'Library', 'Office'],
    ['"医生" in English:', 'Doctor', 'Teacher', 'Lawyer', 'Nurse'],
    ['"音乐" in English:', 'Music', 'Art', 'Dance', 'Movie'],
    ['"重要" in English:', 'Important', 'Difficult', 'Easy', 'Interesting'],
    ['"机会" in English:', 'Opportunity', 'Problem', 'Challenge', 'Solution'],
    ['"经验" in English:', 'Experience', 'Education', 'Knowledge', 'Skill'],
    ['"成功" in English:', 'Success', 'Failure', 'Victory', 'Achievement'],
    ['"环境" in English:', 'Environment', 'Nature', 'Weather', 'Climate'],
    ['"文化" in English:', 'Culture', 'History', 'Tradition', 'Custom'],
    ['"健康" in English:', 'Health', 'Wealth', 'Happiness', 'Fitness'],
    ['"幸福" in English:', 'Happiness', 'Sadness', 'Anger', 'Fear'],
    ['"未来" in English:', 'Future', 'Past', 'Present', 'Yesterday'],
    ['"自由" in English:', 'Freedom', 'Liberty', 'Captivity', 'Prison'],
    ['"知识" in English:', 'Knowledge', 'Wisdom', 'Information', 'Power'],
    ['"和平" in English:', 'Peace', 'War', 'Conflict', 'Battle'],
    ['"梦想" in English:', 'Dream', 'Nightmare', 'Reality', 'Sleep'],
    ['"勇气" in English:', 'Courage', 'Fear', 'Cowardice', 'Weakness'],
    ['"信任" in English:', 'Trust', 'Doubt', 'Suspicion', 'Faithless'],
    ['"尊重" in English:', 'Respect', 'Disrespect', 'Ignore', 'Insult'],
    ['"责任" in English:', 'Responsibility', 'Irresponsibility', 'Freedom', 'Right'],
    ['"友谊" in English:', 'Friendship', 'Enmity', 'Rivalry', 'Hatred'],
    ['"耐心" in English:', 'Patience', 'Impatience', 'Anger', 'Haste'],
    ['"智慧" in English:', 'Wisdom', 'Foolishness', 'Ignorance', 'Stupidity'],
    ['"诚实" in English:', 'Honesty', 'Dishonesty', 'Deception', 'Lie'],
    ['"善良" in English:', 'Kindness', 'Cruelty', 'Meanness', 'Harshness'],
    ['"希望" in English:', 'Hope', 'Despair', 'Doubt', 'Fear'],
    ['"时间" in English:', 'Time', 'Space', 'Money', 'Life'],
    ['"世界" in English:', 'World', 'Country', 'City', 'Village'],
    ['"家人" in English:', 'Family', 'Friend', 'Neighbor', 'Stranger'],
    ['"爱情" in English:', 'Love', 'Hate', 'Like', 'Dislike'],
    ['"生活" in English:', 'Life', 'Death', 'Birth', 'Dream'],
  ],
  medium: [
    ['"勉为其难" means:', 'Do something against one\'s will', 'Work hard willingly', 'Help others happily', 'Finish tasks quickly'],
    ['"脱颖而出" means:', 'Stand out from the crowd', 'Fall behind', 'Escape danger', 'Move forward slowly'],
    ['"实事求是" means:', 'Be practical and realistic', 'Tell lies', 'Be imaginative', 'Follow rules blindly'],
    ['"未雨绸缪" means:', 'Prepare before it rains', 'Act after the fact', 'Wait for instructions', 'Rely on luck'],
    ['"事半功倍" means:', 'Get twice result with half effort', 'Work twice as hard', 'Fail despite effort', 'Take twice as long'],
    ['"画蛇添足" means:', 'Add unnecessary details that spoil', 'Improve a painting', 'Create art carefully', 'Finish work perfectly'],
    ['"半途而废" means:', 'Give up halfway', 'Complete fully', 'Rest in between', 'Start over again'],
    ['"一见钟情" means:', 'Love at first sight', 'Friendship forever', 'Hate at first meeting', 'Meet by chance'],
    ['"胸有成竹" means:', 'Have a well-thought-out plan', 'Be confused', 'Draw bamboo well', 'Be physically strong'],
    ['"对牛弹琴" means:', 'Cast pearls before swine', 'Play music for animals', 'Teach effectively', 'Communicate clearly'],
    ['"锦上添花" means:', 'Add brilliance to splendor', 'Spoil a good thing', 'Start from scratch', 'End in failure'],
    ['"雪中送炭" means:', 'Help in time of need', 'Add ice to snow', 'Give unnecessary help', 'Cause more trouble'],
    ['"百闻不如一见" means:', 'Seeing is believing', 'Hearing is important', 'Words are powerful', 'Trust what people say'],
    ['"熟能生巧" means:', 'Practice makes perfect', 'Perfect comes naturally', 'Natural talent is enough', 'Practice is useless'],
    ['"一心二用" means:', 'Multitask', 'Focus deeply', 'Be single-minded', 'Avoid distraction'],
    ['"入乡随俗" means:', 'When in Rome, do as Romans do', 'Stay true to yourself', 'Ignore local customs', 'Travel widely'],
    ['"口若悬河" means:', 'Speak eloquently and fluently', 'Be silent', 'Speak quietly', 'Drink from a river'],
    ['"柳暗花明" means:', 'A new vista appears after hardship', 'Flowers bloom in spring', 'Darkness follows light', 'Nature is beautiful'],
    ['"百花齐放" means:', 'All flowers bloom together', 'Competition is fierce', 'One stands out', 'Slow growth'],
    ['"取长补短" means:', 'Learn from others\' strengths', 'Take the long way', 'Ignore weaknesses', 'Compete fiercely'],
  ],
  hard: [
    ['"饮鸩止渴" means:', 'Seek relief regardless of consequences', 'Drink when thirsty', 'Find permanent solution', 'Quench thirst properly'],
    ['"纸上谈兵" means:', 'Empty theoretical talk', 'Write military strategy', 'Practical experience', 'Study hard'],
    ['"班门弄斧" means:', 'Show off in front of an expert', 'Teach a beginner', 'Learn from a master', 'Practice diligently'],
    ['"杯弓蛇影" means:', 'Be paranoid and suspicious', 'Drink wine carefully', 'See things clearly', 'Hunt snakes'],
    ['"破釜沉舟" means:', 'Burn boats and commit irrevocably', 'Start a new journey', 'Destroy old equipment', 'Give up halfway'],
    ['"掩耳盗铃" means:', 'Deceive oneself', 'Steal a bell', 'Cover ears', 'Listen carefully'],
    ['"亡羊补牢" means:', 'Mend fold after sheep lost', 'Give up after loss', 'Count sheep carefully', 'Ignore problems'],
    ['"守株待兔" means:', 'Wait idly for opportunities', 'Hunt actively', 'Protect garden', 'Be patient'],
    ['"刻舟求剑" means:', 'Use outdated methods', 'Carve boat skillfully', 'Search for lost items', 'Make swords'],
    ['"叶公好龙" means:', 'Pretend to like what one fears', 'Love dragons genuinely', 'Collect rare items', 'Tell dragon stories'],
    ['"杞人忧天" means:', 'Worry unnecessarily', 'Be concerned for earth', 'Plan for disaster', 'Show genuine concern'],
    ['"塞翁失马" means:', 'A blessing in disguise', 'Always bad luck', 'Lost everything', 'Never recover'],
    ['"指鹿为马" means:', 'Deliberately misrepresent', 'Identify animals correctly', 'Study zoology', 'Name things properly'],
    ['"卧薪尝胆" means:', 'Endure hardship for revenge', 'Sleep comfortably', 'Taste bitter food', 'Live in luxury'],
    ['"朝三暮四" means:', 'Change one\'s mind frequently', 'Rise early and rest late', 'Count carefully', 'Plan ahead'],
  ],
}

// Listening-style comprehension questions
const listeningQuestions = {
  easy: [
    {
      stem: '[Audio] A: "How are you today?" B: "I\'m great, thanks!" What did B say?',
      answer: "I'm great", options: ["I'm tired", "I'm hungry", "I'm great", "I'm busy"],
    },
    {
      stem: '[Audio] "What time does the meeting start?" "It starts at 3 o\'clock." What time?',
      answer: '3:00', options: ['2:00', '3:00', '4:00', '5:00'],
    },
    {
      stem: '[Audio] "Could I have a cup of coffee please?" "Sure, with milk or sugar?" What does the person want?',
      answer: 'Coffee', options: ['Coffee', 'Tea', 'Water', 'Juice'],
    },
    {
      stem: '[Audio] "How much is this shirt?" "It\'s on sale for $25." What is the price?',
      answer: '$25', options: ['$15', '$20', '$25', '$30'],
    },
    {
      stem: '[Audio] "Would you like something to eat?" "No, I already had lunch." What does the person mean?',
      answer: 'They are not hungry', options: ['They want more food', 'They are not hungry', 'They want dinner', 'They are cooking'],
    },
    {
      stem: '[Audio] "The weather forecast says it will rain tomorrow." What is the prediction?',
      answer: 'Rain', options: ['Sunshine', 'Snow', 'Cloudy but dry', 'Rain'],
    },
    {
      stem: '[Audio] "Excuse me, where is the bathroom?" "It\'s on the second floor." Where is it?',
      answer: 'Second floor', options: ['Second floor', 'First floor', 'Basement', 'Outside'],
    },
    {
      stem: '[Audio] "I\'m sorry I\'m late. The traffic was terrible." Why is the person late?',
      answer: 'Heavy traffic', options: ['They overslept', 'They forgot', 'Heavy traffic', 'Their car broke down'],
    },
    {
      stem: '[Audio] "Can I have the check please?" What does the person want?',
      answer: 'The bill', options: ['More food', 'The bill', 'A menu', 'A reservation'],
    },
    {
      stem: '[Audio] A: "What do you do?" B: "I\'m a software engineer." What is B\'s job?',
      answer: 'Software engineer', options: ['Teacher', 'Doctor', 'Software engineer', 'Lawyer'],
    },
    {
      stem: '[Audio] "The movie was fantastic! I loved every minute of it." How was the movie?',
      answer: 'Excellent', options: ['Boring', 'Terrible', 'Excellent', 'Average'],
    },
    {
      stem: '[Audio] "I need to buy some milk, bread, and eggs from the grocery store." What item was NOT mentioned?',
      answer: 'Cheese', options: ['Milk', 'Bread', 'Eggs', 'Cheese'],
    },
    {
      stem: '[Audio] "Could you speak more slowly please? I\'m still learning English." What does the speaker want?',
      answer: 'Slower speech', options: ['Faster speech', 'Slower speech', 'Louder speech', 'Written text'],
    },
    {
      stem: '[Audio] "It\'s freezing outside! Make sure to wear a warm coat." What is the weather like?',
      answer: 'Very cold', options: ['Very hot', 'Mild', 'Very cold', 'Rainy'],
    },
    {
      stem: '[Audio] "My flight leaves at 6 AM, so I need to wake up at 3:30." When is the flight?',
      answer: '6:00 AM', options: ['3:30 AM', '6:00 AM', '6:00 PM', '3:30 PM'],
    },
  ],
  medium: [
    {
      stem: '[Audio] "Despite the economic downturn, the company managed to increase its revenue by 15% this quarter." What happened?',
      answer: 'Revenue increased 15%', options: ['Revenue decreased', 'Revenue increased 15%', 'The company shut down', 'Profits stayed flat'],
    },
    {
      stem: '[Audio] "Professor, could you elaborate on the implications of your research for renewable energy?" What is being asked?',
      answer: 'To explain research implications', options: ['To stop the research', 'To explain research implications', 'To cancel the class', 'To give a grade'],
    },
    {
      stem: '[Audio] "The renovation is behind schedule. We\'re looking at another three weeks at minimum." What does this mean?',
      answer: 'The project is delayed', options: ['The project is ahead of schedule', 'The project is delayed', 'The project is complete', 'The project is on time'],
    },
    {
      stem: '[Audio] "I\'d recommend diversifying your portfolio rather than putting everything into one stock." What is the advice?',
      answer: 'Spread investments across multiple options', options: ['Invest in one stock only', 'Spread investments across multiple options', 'Sell all stocks', 'Stop investing entirely'],
    },
    {
      stem: '[Audio] "The manuscript has been peer-reviewed and accepted for publication pending minor revisions." What is the status?',
      answer: 'Accepted with minor changes needed', options: ['Rejected completely', 'Accepted with minor changes needed', 'Still waiting for review', 'Published already'],
    },
    {
      stem: '[Audio] "Given the current trajectory, we anticipate reaching the target by Q3 next year." What is the prediction?',
      answer: 'Target will be reached in Q3 next year', options: ['Target will be reached in Q3 next year', 'Target has been reached', 'Target will never be reached', 'Target was already missed'],
    },
  ],
  hard: [
    {
      stem: '[Audio] "The epistemological foundations of this paradigm shift necessitate a fundamental reexamination of our methodological premises." What is being argued?',
      answer: 'We need to reexamine our methods', options: ['Our methods are perfect', 'We need to reexamine our methods', 'The paradigm is irrelevant', 'No changes are needed'],
    },
    {
      stem: '[Audio] "The confluence of geopolitical tensions and supply chain disruptions has precipitated an unprecedented inflationary milieu." What is described?',
      answer: 'A combination of factors causing inflation', options: ['A peaceful global situation', 'A combination of factors causing inflation', 'Only supply chain problems', 'Only political problems'],
    },
    {
      stem: '[Audio] "While the prima facie evidence appears compelling, a more nuanced analysis reveals significant methodological flaws." What is the claim?',
      answer: 'The evidence looks good but has flaws', options: ['The evidence is flawless', 'The evidence looks good but has flaws', 'There is no evidence', 'The analysis is complete'],
    },
    {
      stem: '[Audio] "The symbiotic relationship between technological innovation and socioeconomic stratification warrants rigorous longitudinal investigation." What is the main idea?',
      answer: 'Tech innovation and social inequality should be studied together over time', options: ['Technology is always good', 'Tech innovation and social inequality should be studied together over time', 'Socioeconomic issues are not important', 'Research is unnecessary'],
    },
  ],
}

// ===== BULK QUESTION GENERATOR: Adds 700+ more questions =====
const bulkVocabBank: string[][] = [
  // Easy words with synonyms and distractors
  ['Abandon', 'Give up', 'Keep', 'Protect', 'Cherish'],
  ['Absorb', 'Soak up', 'Release', 'Repel', 'Eject'],
  ['Achieve', 'Accomplish', 'Fail', 'Lose', 'Quit'],
  ['Adapt', 'Adjust', 'Resist', 'Refuse', 'Reject'],
  ['Admire', 'Respect', 'Despise', 'Scorn', 'Hate'],
  ['Admit', 'Confess', 'Deny', 'Refuse', 'Reject'],
  ['Adopt', 'Take on', 'Abandon', 'Reject', 'Ignore'],
  ['Affect', 'Influence', 'Ignore', 'Avoid', 'Neglect'],
  ['Afford', 'Pay for', 'Lack', 'Need', 'Want'],
  ['Agree', 'Consent', 'Disagree', 'Argue', 'Fight'],
  ['Aim', 'Target', 'Miss', 'Ignore', 'Avoid'],
  ['Alter', 'Change', 'Keep', 'Preserve', 'Fix'],
  ['Amaze', 'Astonish', 'Bore', 'Tire', 'Disappoint'],
  ['Amuse', 'Entertain', 'Bore', 'Annoy', 'Irritate'],
  ['Annoy', 'Irritate', 'Please', 'Delight', 'Charm'],
  ['Apologize', 'Say sorry', 'Blame', 'Accuse', 'Attack'],
  ['Appear', 'Seem', 'Vanish', 'Hide', 'Disappear'],
  ['Applaud', 'Clap for', 'Boo', 'Jeer', 'Mock'],
  ['Apply', 'Put in for', 'Withdraw', 'Ignore', 'Skip'],
  ['Approve', 'Agree to', 'Reject', 'Veto', 'Deny'],
  ['Argue', 'Dispute', 'Agree', 'Accept', 'Concede'],
  ['Arrange', 'Organize', 'Mess up', 'Disrupt', 'Scatter'],
  ['Arrive', 'Reach', 'Leave', 'Depart', 'Go'],
  ['Attack', 'Assault', 'Defend', 'Protect', 'Guard'],
  ['Attempt', 'Try', 'Avoid', 'Ignore', 'Skip'],
  ['Attract', 'Draw in', 'Repel', 'Push away', 'Disgust'],
  ['Avoid', 'Stay away', 'Seek', 'Pursue', 'Chase'],
  ['Bake', 'Cook in oven', 'Freeze', 'Chill', 'Cool'],
  ['Bargain', 'Negotiate', 'Pay full', 'Ignore', 'Accept'],
  ['Battle', 'Fight', 'Surrender', 'Yield', 'Give up'],
  ['Behave', 'Act properly', 'Misbehave', 'Act out', 'Disobey'],
  ['Believe', 'Trust', 'Doubt', 'Question', 'Suspect'],
  ['Belong', 'Be owned by', 'Stray', 'Wander', 'Leave'],
  ['Bend', 'Curve', 'Straighten', 'Flatten', 'Stiffen'],
  ['Benefit', 'Gain', 'Lose', 'Suffer', 'Worsen'],
  ['Betray', 'Be disloyal', 'Support', 'Defend', 'Protect'],
  ['Bind', 'Tie together', 'Release', 'Free', 'Loosen'],
  ['Bite', 'Nip', 'Release', 'Let go', 'Free'],
  ['Blame', 'Accuse', 'Defend', 'Support', 'Praise'],
  ['Blend', 'Mix together', 'Separate', 'Divide', 'Split'],
  ['Bless', 'Give favor', 'Curse', 'Damn', 'Condemn'],
  ['Block', 'Obstruct', 'Allow', 'Permit', 'Enable'],
  ['Blush', 'Go red', 'Pale', 'Whiten', 'Fade'],
  ['Boast', 'Brag', 'Be humble', 'Downplay', 'Hide'],
  ['Boil', 'Heat to bubble', 'Freeze', 'Cool', 'Chill'],
  ['Borrow', 'Take temporarily', 'Lend', 'Give', 'Return'],
  ['Bounce', 'Spring back', 'Stick', 'Stay', 'Settle'],
  ['Bound', 'Jump', 'Crawl', 'Creep', 'Stay'],
  ['Breed', 'Produce young', 'Die out', 'End', 'Stop'],
  ['Broadcast', 'Transmit', 'Receive', 'Hide', 'Conceal'],
  ['Bruise', 'Injure lightly', 'Heal', 'Cure', 'Fix'],
  ['Bury', 'Put underground', 'Dig up', 'Exhume', 'Unearth'],
  ['Capture', 'Catch', 'Release', 'Free', 'Let go'],
  ['Carve', 'Cut shapes', 'Smooth', 'Flatten', 'Fill'],
  ['Celebrate', 'Have a party', 'Mourn', 'Grieve', 'Lament'],
  ['Challenge', 'Dare', 'Accept', 'Agree', 'Concede'],
  ['Charm', 'Delight', 'Repel', 'Disgust', 'Offend'],
  ['Cheat', 'Act dishonestly', 'Play fair', 'Be honest', 'Follow rules'],
  ['Cheer', 'Shout joyfully', 'Boo', 'Jeer', 'Mock'],
  ['Cherish', 'Treasure', 'Neglect', 'Ignore', 'Abandon'],
  ['Chop', 'Cut roughly', 'Smooth', 'Polish', 'Refine'],
  ['Claim', 'State as true', 'Deny', 'Dispute', 'Reject'],
  ['Clarify', 'Make clear', 'Confuse', 'Obscure', 'Cloud'],
  ['Clash', 'Conflict', 'Harmonize', 'Agree', 'Match'],
  ['Cling', 'Hold tightly', 'Release', 'Let go', 'Drop'],
  ['Collapse', 'Fall down', 'Stand', 'Rise', 'Hold'],
  ['Combine', 'Join together', 'Separate', 'Divide', 'Split'],
  ['Command', 'Order', 'Obey', 'Follow', 'Submit'],
  ['Commit', 'Promise fully', 'Abandon', 'Desert', 'Walk away'],
  ['Complain', 'Express discontent', 'Praise', 'Compliment', 'Appreciate'],
  ['Complicate', 'Make difficult', 'Simplify', 'Ease', 'Clarify'],
  ['Concentrate', 'Focus', 'Scatter', 'Disperse', 'Diffuse'],
  ['Concern', 'Worry about', 'Ignore', 'Neglect', 'Dismiss'],
  ['Conclude', 'Finish', 'Begin', 'Start', 'Open'],
  ['Confirm', 'Verify', 'Deny', 'Contradict', 'Disprove'],
  ['Confuse', 'Bewilder', 'Clarify', 'Explain', 'Enlighten'],
  ['Connect', 'Link together', 'Separate', 'Disconnect', 'Split'],
  ['Conquer', 'Defeat fully', 'Surrender', 'Yield', 'Submit'],
  ['Conserve', 'Save up', 'Waste', 'Squander', 'Spend'],
  ['Construct', 'Build', 'Destroy', 'Demolish', 'Ruin'],
  ['Consult', 'Ask advice', 'Ignore', 'Decide alone', 'Act solo'],
  ['Contain', 'Hold inside', 'Release', 'Spill', 'Leak'],
  ['Contrast', 'Show difference', 'Blend', 'Merge', 'Unify'],
  ['Cooperate', 'Work together', 'Compete', 'Fight', 'Oppose'],
  ['Cope', 'Manage difficulty', 'Fail', 'Collapse', 'Break down'],
  ['Corrupt', 'Make dishonest', 'Purify', 'Cleanse', 'Improve'],
  ['Create', 'Make something', 'Destroy', 'Ruin', 'Wreck'],
  ['Criticize', 'Find fault', 'Praise', 'Compliment', 'Applaud'],
  ['Crumble', 'Fall apart', 'Hold together', 'Stay solid', 'Remain'],
  ['Crush', 'Press hard', 'Release', 'Free', 'Liberate'],
  ['Cure', 'Make healthy', 'Sicken', 'Harm', 'Poison'],
  ['Damage', 'Harm', 'Repair', 'Fix', 'Mend'],
  ['Debate', 'Argue formally', 'Agree', 'Accept', 'Concede'],
  ['Decay', 'Rot away', 'Flourish', 'Thrive', 'Grow'],
  ['Deceive', 'Trick', 'Tell truth', 'Be honest', 'Be real'],
  ['Declare', 'Announce', 'Hide', 'Conceal', 'Suppress'],
  ['Decline', 'Refuse politely', 'Accept', 'Agree', 'Welcome'],
  ['Decorate', 'Make beautiful', 'Ruin', 'Mess up', 'Deface'],
  ['Defeat', 'Beat', 'Lose to', 'Surrender to', 'Yield to'],
  ['Defend', 'Protect', 'Attack', 'Assault', 'Invade'],
  ['Define', 'Give meaning', 'Confuse', 'Obscure', 'Vague'],
  ['Delay', 'Postpone', 'Advance', 'Speed up', 'Rush'],
  ['Delight', 'Please greatly', 'Disgust', 'Offend', 'Repulse'],
  ['Demand', 'Insist on', 'Offer', 'Suggest', 'Propose'],
  ['Deny', 'Say no to', 'Admit', 'Confess', 'Acknowledge'],
  ['Depart', 'Leave', 'Arrive', 'Come', 'Reach'],
  ['Depend', 'Rely on', 'Be independent', 'Stand alone', 'Separate'],
  ['Deposit', 'Put in', 'Withdraw', 'Take out', 'Remove'],
  ['Describe', 'Tell about', 'Hide', 'Conceal', 'Withhold'],
  ['Deserve', 'Be worthy of', 'Lose right', 'Forfeit', 'Be denied'],
  ['Desire', 'Want strongly', 'Dislike', 'Reject', 'Abhor'],
  ['Destroy', 'Ruin completely', 'Build', 'Create', 'Construct'],
  ['Detect', 'Notice', 'Miss', 'Overlook', 'Ignore'],
  ['Develop', 'Grow', 'Shrink', 'Decline', 'Decrease'],
  ['Devote', 'Dedicate to', 'Neglect', 'Ignore', 'Abandon'],
  ['Disappear', 'Vanish', 'Appear', 'Emerge', 'Show up'],
  ['Discipline', 'Train strictly', 'Spoil', 'Indulge', 'Pamper'],
  ['Discover', 'Find first', 'Hide', 'Lose', 'Conceal'],
  ['Discuss', 'Talk about', 'Ignore', 'Avoid', 'Skip'],
  ['Dismiss', 'Send away', 'Accept', 'Welcome', 'Embrace'],
  ['Display', 'Show', 'Hide', 'Conceal', 'Cover'],
  ['Distribute', 'Give out', 'Collect', 'Gather', 'Hoard'],
  ['Disturb', 'Interrupt', 'Calm', 'Soothe', 'Quiet'],
  ['Donate', 'Give freely', 'Take', 'Steal', 'Keep'],
  ['Drag', 'Pull along', 'Push', 'Shove', 'Propel'],
  ['Drain', 'Remove liquid', 'Fill', 'Flood', 'Saturate'],
  ['Drift', 'Move slowly', 'Rush', 'Speed', 'Race'],
  ['Drown', 'Die in water', 'Survive', 'Live', 'Thrive'],
  ['Ease', 'Make comfortable', 'Strain', 'Stress', 'Tense'],
  ['Educate', 'Teach', 'Mislead', 'Confuse', 'Deceive'],
  ['Eliminate', 'Remove completely', 'Add', 'Include', 'Keep'],
  ['Embrace', 'Hug warmly', 'Reject', 'Push away', 'Shun'],
  ['Emerge', 'Come out', 'Hide', 'Disappear', 'Vanish'],
  ['Employ', 'Hire for work', 'Fire', 'Dismiss', 'Release'],
  ['Enable', 'Make possible', 'Prevent', 'Block', 'Stop'],
  ['Encounter', 'Meet by chance', 'Plan to meet', 'Arrange', 'Schedule'],
  ['Encourage', 'Give hope', 'Discourage', 'Depress', 'Demotivate'],
  ['Endure', 'Last through', 'Give up', 'Quit', 'Collapse'],
  ['Engage', 'Involve in', 'Detach', 'Disconnect', 'Remove'],
  ['Enhance', 'Make better', 'Worsen', 'Decrease', 'Reduce'],
  ['Enjoy', 'Take pleasure', 'Dislike', 'Hate', 'Despise'],
  ['Ensure', 'Make certain', 'Risk', 'Gamble', 'Chance'],
  ['Entertain', 'Amuse', 'Bore', 'Tire', 'Weary'],
  ['Escape', 'Get away', 'Stay', 'Remain', 'Endure'],
  ['Establish', 'Set up firmly', 'Destroy', 'Dismantle', 'End'],
  ['Evaluate', 'Judge value', 'Ignore', 'Overlook', 'Skip'],
  ['Evolve', 'Develop slowly', 'Stay same', 'Remain', 'Stop'],
  ['Examine', 'Look closely', 'Glance', 'Skim', 'Miss'],
  ['Exceed', 'Go beyond', 'Fall short', 'Fail', 'Miss'],
  ['Exchange', 'Trade', 'Keep', 'Hold', 'Retain'],
  ['Excite', 'Thrill', 'Bore', 'Calm', 'Soothe'],
  ['Exclude', 'Leave out', 'Include', 'Add', 'Welcome'],
  ['Excuse', 'Forgive', 'Blame', 'Accuse', 'Condemn'],
  ['Exist', 'Be alive', 'Die', 'Cease', 'End'],
  ['Expand', 'Make bigger', 'Shrink', 'Reduce', 'Contract'],
  ['Expect', 'Think will happen', 'Doubt', 'Question', 'Suspect'],
  ['Explode', 'Burst apart', 'Implode', 'Collapse', 'Contract'],
  ['Explore', 'Search new areas', 'Ignore', 'Avoid', 'Skip'],
  ['Export', 'Send out', 'Import', 'Bring in', 'Receive'],
  ['Expose', 'Reveal truth', 'Hide', 'Cover', 'Conceal'],
  ['Extend', 'Make longer', 'Shorten', 'Reduce', 'Cut back'],
  ['Fade', 'Lose color', 'Brighten', 'Intensify', 'Deepen'],
  ['Faint', 'Pass out', 'Wake up', 'Revive', 'Recover'],
  ['Fascinate', 'Captivate', 'Bore', 'Tire', 'Repel'],
  ['Fasten', 'Secure firmly', 'Loosen', 'Undo', 'Release'],
  ['Favor', 'Prefer', 'Oppose', 'Reject', 'Dislike'],
  ['Fear', 'Be scared of', 'Love', 'Welcome', 'Embrace'],
  ['Feed', 'Give food to', 'Starve', 'Famish', 'Deprive'],
  ['Fetch', 'Go get', 'Bring back', 'Leave', 'Abandon'],
  ['Fight', 'Battle against', 'Surrender', 'Give up', 'Yield'],
  ['Finance', 'Provide money', 'Defund', 'Starve', 'Deprive'],
  ['Flatter', 'Praise insincerely', 'Insult', 'Criticize', 'Mock'],
  ['Flee', 'Run away', 'Stay', 'Remain', 'Approach'],
  ['Flourish', 'Thrive', 'Wither', 'Decline', 'Fade'],
  ['Flow', 'Move smoothly', 'Stop', 'Freeze', 'Clog'],
  ['Fool', 'Trick someone', 'Enlighten', 'Inform', 'Teach'],
  ['Forbid', 'Not allow', 'Permit', 'Allow', 'Authorize'],
  ['Force', 'Make someone do', 'Persuade', 'Convince', 'Ask'],
  ['Forecast', 'Predict', 'Ignore trends', 'Guess randomly', 'Disregard'],
  ['Forgive', 'Pardon', 'Blame', 'Resent', 'Hold grudge'],
  ['Frighten', 'Scare', 'Comfort', 'Soothe', 'Calm'],
  ['Frustrate', 'Annoy by blocking', 'Satisfy', 'Fulfill', 'Help'],
  ['Fulfill', 'Achieve fully', 'Fail', 'Miss', 'Fall short'],
  ['Gather', 'Collect together', 'Scatter', 'Disperse', 'Spread'],
  ['Gaze', 'Stare at', 'Glance', 'Peek', 'Ignore'],
  ['Generate', 'Produce', 'Destroy', 'Consume', 'Use up'],
  ['Glimpse', 'See briefly', 'Stare', 'Gaze', 'Study'],
  ['Govern', 'Rule over', 'Follow', 'Obey', 'Submit'],
  ['Graduate', 'Complete studies', 'Drop out', 'Quit', 'Fail'],
  ['Grant', 'Give formally', 'Refuse', 'Deny', 'Withhold'],
  ['Grasp', 'Hold firmly', 'Drop', 'Release', 'Let go'],
  ['Greet', 'Welcome', 'Ignore', 'Snub', 'Shun'],
  ['Grieve', 'Mourn loss', 'Celebrate', 'Rejoice', 'Party'],
  ['Grip', 'Hold tight', 'Release', 'Loosen', 'Free'],
  ['Grow', 'Increase in size', 'Shrink', 'Decrease', 'Wither'],
  ['Guarantee', 'Promise fully', 'Risk', 'Gamble', 'Chance'],
  ['Guard', 'Protect from', 'Attack', 'Assault', 'Invade'],
  ['Guide', 'Show the way', 'Mislead', 'Confuse', 'Deceive'],
  ['Handle', 'Manage', 'Mishandle', 'Botch', 'Fumble'],
  ['Hasten', 'Speed up', 'Slow down', 'Delay', 'Linger'],
  ['Haunt', 'Visit as ghost', 'Comfort', 'Soothe', 'Reassure'],
  ['Heal', 'Make healthy', 'Harm', 'Hurt', 'Wound'],
  ['Heap', 'Pile up', 'Scatter', 'Spread', 'Disperse'],
  ['Hesitate', 'Pause uncertainly', 'Decide quickly', 'Rush in', 'Act fast'],
  ['Hinder', 'Get in way of', 'Help', 'Aid', 'Assist'],
  ['Hint', 'Suggest indirectly', 'State directly', 'Declare', 'Proclaim'],
  ['Honor', 'Show respect', 'Dishonor', 'Disrespect', 'Shame'],
  ['Hug', 'Embrace warmly', 'Reject', 'Push', 'Shove'],
  ['Humiliate', 'Shame publicly', 'Honor', 'Praise', 'Exalt'],
  ['Hunt', 'Search for prey', 'Protect', 'Guard', 'Shield'],
  ['Hurry', 'Move quickly', 'Slow down', 'Dawdle', 'Linger'],
  ['Imitate', 'Copy actions', 'Be original', 'Innovate', 'Create'],
  ['Imply', 'Suggest without saying', 'State directly', 'Say outright', 'Declare'],
  ['Impose', 'Force upon', 'Remove', 'Lift', 'Free from'],
  ['Impress', 'Make impact on', 'Disappoint', 'Underwhelm', 'Bore'],
  ['Improve', 'Make better', 'Worsen', 'Degrade', 'Reduce'],
  ['Include', 'Contain as part', 'Exclude', 'Omit', 'Leave out'],
  ['Increase', 'Make larger', 'Decrease', 'Reduce', 'Shrink'],
  ['Indicate', 'Point out', 'Hide', 'Conceal', 'Mask'],
  ['Infect', 'Spread disease to', 'Cure', 'Heal', 'Treat'],
  ['Inform', 'Tell about', 'Hide from', 'Conceal', 'Withhold'],
  ['Inhabit', 'Live in', 'Vacate', 'Leave', 'Empty'],
  ['Inherit', 'Receive from past', 'Lose', 'Forfeit', 'Give away'],
  ['Initiate', 'Start off', 'End', 'Conclude', 'Finish'],
  ['Inject', 'Push fluid in', 'Extract', 'Withdraw', 'Remove'],
  ['Injure', 'Hurt physically', 'Heal', 'Cure', 'Mend'],
  ['Inspect', 'Look over carefully', 'Overlook', 'Miss', 'Skip'],
  ['Inspire', 'Motivate greatly', 'Discourage', 'Depress', 'Deject'],
  ['Install', 'Set up for use', 'Remove', 'Uninstall', 'Delete'],
  ['Instruct', 'Give directions', 'Confuse', 'Mislead', 'Deceive'],
  ['Insult', 'Offend with words', 'Compliment', 'Praise', 'Flatter'],
  ['Intend', 'Plan to do', 'Drift', 'Wander', 'Ramble'],
  ['Interfere', 'Get in way', 'Help', 'Assist', 'Aid'],
  ['Interpret', 'Explain meaning', 'Misunderstand', 'Confuse', 'Distort'],
  ['Interrupt', 'Break into', 'Let finish', 'Wait', 'Allow'],
  ['Introduce', 'Present someone', 'Ignore', 'Snub', 'Overlook'],
  ['Invade', 'Enter by force', 'Withdraw', 'Retreat', 'Leave'],
  ['Invent', 'Create something new', 'Copy', 'Replicate', 'Duplicate'],
  ['Invest', 'Put money into', 'Spend', 'Waste', 'Squander'],
  ['Investigate', 'Look into deeply', 'Ignore', 'Overlook', 'Skip'],
  ['Invite', 'Ask to come', 'Exclude', 'Snub', 'Reject'],
  ['Involve', 'Include actively', 'Exclude', 'Detach', 'Separate'],
  ['Irritate', 'Annoy slightly', 'Please', 'Delight', 'Soothe'],
  ['Isolate', 'Separate from others', 'Include', 'Connect', 'Join'],
  ['Jealous', 'Envious of', 'Content', 'Satisfied', 'Happy for'],
  ['Journey', 'Travel somewhere', 'Stay put', 'Remain', 'Settle'],
  ['Judge', 'Form opinion on', 'Ignore', 'Dismiss', 'Overlook'],
  ['Justify', 'Give reason for', 'Condemn', 'Blame', 'Attack'],
  ['Kick', 'Strike with foot', 'Embrace', 'Hug', 'Caress'],
  ['Knock', 'Hit surface', 'Caress', 'Stroke', 'Pat'],
  ['Label', 'Put tag on', 'Ignore', 'Mislabel', 'Skip'],
  ['Lack', 'Not have enough', 'Have plenty', 'Abound', 'Overflow'],
  ['Launch', 'Start something', 'End', 'Terminate', 'Stop'],
  ['Lead', 'Guide forward', 'Follow', 'Trail', 'Chase'],
  ['Leak', 'Let liquid out', 'Seal', 'Contain', 'Hold'],
  ['Lean', 'Tilt to side', 'Straighten', 'Stand upright', 'Center'],
  ['Leap', 'Jump high', 'Crawl', 'Creep', 'Slither'],
  ['Liberate', 'Set free', 'Enslave', 'Capture', 'Imprison'],
  ['Limit', 'Restrict', 'Expand', 'Free', 'Release'],
  ['Locate', 'Find position', 'Lose', 'Mislay', 'Miss'],
  ['Long', 'Yearn for', 'Despise', 'Detest', 'Reject'],
  ['Loosen', 'Make less tight', 'Tighten', 'Fasten', 'Secure'],
  ['Lure', 'Attract deceptively', 'Repel', 'Warn', 'Deter'],
  ['Magnify', 'Make bigger', 'Reduce', 'Shrink', 'Minimize'],
  ['Maintain', 'Keep in state', 'Neglect', 'Abandon', 'Ignore'],
  ['Manufacture', 'Make in factory', 'Destroy', 'Wreck', 'Ruin'],
  ['Master', 'Become expert at', 'Fail at', 'Begin', 'Attempt'],
  ['Match', 'Go together', 'Clash', 'Conflict', 'Disagree'],
  ['Mature', 'Grow up', 'Regress', 'Decline', 'Weaken'],
  ['Measure', 'Find size of', 'Guess', 'Estimate', 'Approximate'],
  ['Melt', 'Turn to liquid', 'Freeze', 'Solidify', 'Harden'],
  ['Mend', 'Fix something', 'Break', 'Damage', 'Ruin'],
  ['Mislead', 'Give wrong idea', 'Inform', 'Enlighten', 'Guide correctly'],
  ['Miss', 'Fail to hit', 'Hit', 'Strike', 'Connect'],
  ['Mix', 'Combine together', 'Separate', 'Divide', 'Split'],
  ['Modify', 'Make changes to', 'Preserve', 'Keep same', 'Maintain'],
  ['Monitor', 'Watch carefully', 'Ignore', 'Neglect', 'Overlook'],
  ['Motivate', 'Inspire to act', 'Discourage', 'Depress', 'Demotivate'],
  ['Multiply', 'Increase greatly', 'Divide', 'Reduce', 'Decrease'],
  ['Murmur', 'Speak softly', 'Shout', 'Yell', 'Scream'],
  ['Neglect', 'Fail to care for', 'Tend', 'Nurture', 'Care for'],
  ['Negotiate', 'Discuss terms', 'Accept immediately', 'Refuse to talk', 'Dictate'],
  ['Notify', 'Tell formally', 'Hide from', 'Conceal', 'Keep secret'],
  ['Nourish', 'Feed and support', 'Starve', 'Deprive', 'Neglect'],
  ['Obey', 'Follow orders', 'Disobey', 'Rebel', 'Defy'],
  ['Object', 'Express opposition', 'Agree', 'Accept', 'Approve'],
  ['Observe', 'Watch closely', 'Ignore', 'Miss', 'Overlook'],
  ['Obstruct', 'Block way of', 'Clear', 'Open', 'Free'],
  ['Occupy', 'Take up space', 'Vacate', 'Empty', 'Leave'],
  ['Offend', 'Upset someone', 'Please', 'Delight', 'Charm'],
  ['Oppose', 'Be against', 'Support', 'Back', 'Endorse'],
  ['Organize', 'Arrange neatly', 'Mess up', 'Disorder', 'Scatter'],
  ['Overcome', 'Defeat obstacle', 'Succumb', 'Yield', 'Give in'],
  ['Overlook', 'Fail to notice', 'Notice', 'Spot', 'Detect'],
  ['Participate', 'Take part in', 'Opt out', 'Skip', 'Avoid'],
  ['Penetrate', 'Go through into', 'Bounce off', 'Deflect', 'Skim'],
  ['Perceive', 'Become aware of', 'Miss', 'Overlook', 'Ignore'],
  ['Perform', 'Carry out action', 'Fail', 'Underperform', 'Neglect'],
  ['Persuade', 'Convince someone', 'Dissuade', 'Discourage', 'Deter'],
  ['Plant', 'Put in ground', 'Uproot', 'Remove', 'Extract'],
  ['Plead', 'Beg earnestly', 'Demand', 'Order', 'Command'],
  ['Plunge', 'Dive into quickly', 'Withdraw', 'Retreat', 'Back out'],
  ['Poison', 'Make toxic', 'Purify', 'Cleanse', 'Detoxify'],
  ['Polish', 'Make shiny', 'Tarnish', 'Dull', 'Roughen'],
  ['Possess', 'Own something', 'Lack', 'Need', 'Want'],
  ['Postpone', 'Delay to later', 'Advance', 'Bring forward', 'Rush'],
  ['Praise', 'Express approval', 'Criticize', 'Blame', 'Condemn'],
  ['Predict', 'Say will happen', 'Ignore future', 'Guess randomly', 'Dismiss'],
  ['Preserve', 'Keep in state', 'Destroy', 'Ruin', 'Demolish'],
  ['Pretend', 'Act as if', 'Be genuine', 'Be real', 'Be authentic'],
  ['Prevent', 'Stop from happening', 'Allow', 'Enable', 'Permit'],
  ['Proceed', 'Continue forward', 'Stop', 'Halt', 'Cease'],
  ['Produce', 'Create something', 'Destroy', 'Consume', 'Use up'],
  ['Prohibit', 'Ban officially', 'Allow', 'Permit', 'Authorize'],
  ['Promote', 'Advance position', 'Demote', 'Downgrade', 'Reduce'],
  ['Protect', 'Keep safe', 'Endanger', 'Harm', 'Expose'],
  ['Protest', 'Object publicly', 'Support', 'Accept', 'Endorse'],
  ['Provide', 'Give what needed', 'Deprive', 'Withhold', 'Deny'],
  ['Punish', 'Give penalty', 'Reward', 'Praise', 'Forgive'],
  ['Pursue', 'Chase after', 'Avoid', 'Flee', 'Escape'],
  ['Qualify', 'Meet requirements', 'Fail', 'Fall short', 'Disqualify'],
  ['Quit', 'Stop doing', 'Continue', 'Persist', 'Persevere'],
  ['Raise', 'Lift up', 'Lower', 'Drop', 'Decrease'],
  ['Reach', 'Arrive at', 'Depart', 'Leave', 'Exit'],
  ['Realize', 'Become aware', 'Ignore', 'Overlook', 'Miss'],
  ['Rebel', 'Rise against', 'Obey', 'Submit', 'Comply'],
  ['Recall', 'Remember', 'Forget', 'Overlook', 'Miss'],
  ['Receive', 'Get from others', 'Give', 'Send', 'Donate'],
  ['Recognize', 'Identify as known', 'Ignore', 'Overlook', 'Miss'],
  ['Recommend', 'Suggest favorably', 'Warn against', 'Discourage', 'Oppose'],
  ['Recover', 'Get back health', 'Worsen', 'Decline', 'Deteriorate'],
  ['Reduce', 'Make smaller', 'Increase', 'Expand', 'Enlarge'],
  ['Reflect', 'Think deeply', 'Ignore', 'Disregard', 'Dismiss'],
  ['Reform', 'Improve by change', 'Corrupt', 'Ruin', 'Worsen'],
  ['Refuse', 'Say no to', 'Accept', 'Agree', 'Consent'],
  ['Regret', 'Feel sorry for', 'Celebrate', 'Rejoice', 'Be proud'],
  ['Regulate', 'Control by rules', 'Deregulate', 'Free', 'Liberate'],
  ['Reinforce', 'Make stronger', 'Weaken', 'Undermine', 'Erode'],
  ['Reject', 'Turn down', 'Accept', 'Welcome', 'Embrace'],
  ['Relate', 'Connect to', 'Disconnect', 'Separate', 'Detach'],
  ['Relax', 'Become less tense', 'Tense up', 'Stress', 'Strain'],
  ['Release', 'Let go', 'Hold', 'Grip', 'Capture'],
  ['Relieve', 'Ease pain', 'Aggravate', 'Worsen', 'Intensify'],
  ['Rely', 'Depend on', 'Distrust', 'Doubt', 'Question'],
  ['Remain', 'Stay behind', 'Leave', 'Depart', 'Go'],
  ['Remedy', 'Fix problem', 'Worsen', 'Aggravate', 'Harm'],
  ['Remove', 'Take away', 'Add', 'Insert', 'Place'],
  ['Renew', 'Make new again', 'Age', 'Wear out', 'Deteriorate'],
  ['Repair', 'Fix what broken', 'Break', 'Damage', 'Wreck'],
  ['Replace', 'Swap out for', 'Keep', 'Retain', 'Hold onto'],
  ['Represent', 'Stand for', 'Misrepresent', 'Distort', 'Twist'],
  ['Request', 'Ask for politely', 'Demand', 'Order', 'Command'],
  ['Rescue', 'Save from danger', 'Abandon', 'Desert', 'Endanger'],
  ['Resemble', 'Look like', 'Differ from', 'Contrast', 'Oppose'],
  ['Reserve', 'Save for later', 'Use up', 'Spend', 'Waste'],
  ['Resist', 'Fight against', 'Submit', 'Yield', 'Give in'],
  ['Resolve', 'Find solution to', 'Ignore', 'Avoid', 'Skip'],
  ['Respect', 'Show honor to', 'Disrespect', 'Insult', 'Dishonor'],
  ['Respond', 'Answer back', 'Ignore', 'Disregard', 'Dismiss'],
  ['Restore', 'Bring back to original', 'Damage', 'Ruin', 'Destroy'],
  ['Restrict', 'Limit access', 'Free', 'Open', 'Allow'],
  ['Reveal', 'Make known', 'Hide', 'Conceal', 'Cover'],
  ['Revenge', 'Pay back harm', 'Forgive', 'Pardon', 'Let go'],
  ['Reward', 'Give prize to', 'Punish', 'Penalize', 'Fine'],
  ['Ridicule', 'Mock someone', 'Praise', 'Admire', 'Respect'],
  ['Roam', 'Wander around', 'Stay put', 'Settle', 'Stop'],
  ['Rob', 'Steal from', 'Give to', 'Donate', 'Contribute'],
  ['Rot', 'Decay away', 'Flourish', 'Thrive', 'Bloom'],
  ['Ruin', 'Destroy completely', 'Build', 'Create', 'Repair'],
  ['Rush', 'Hurry quickly', 'Slow down', 'Dawdle', 'Linger'],
  ['Sacrifice', 'Give up for cause', 'Keep', 'Hold', 'Retain'],
  ['Satisfy', 'Meet needs of', 'Disappoint', 'Fail', 'Underwhelm'],
  ['Scare', 'Frighten', 'Comfort', 'Reassure', 'Calm'],
  ['Scatter', 'Spread out', 'Gather', 'Collect', 'Group'],
  ['Scold', 'Tell off angrily', 'Praise', 'Compliment', 'Applaud'],
  ['Search', 'Look for carefully', 'Ignore', 'Overlook', 'Dismiss'],
  ['Secure', 'Make safe', 'Endanger', 'Risk', 'Expose'],
  ['Seize', 'Take by force', 'Release', 'Free', 'Let go'],
  ['Select', 'Choose carefully', 'Reject', 'Refuse', 'Dismiss all'],
  ['Separate', 'Split apart', 'Join', 'Combine', 'Unite'],
  ['Serve', 'Provide help to', 'Ignore', 'Neglect', 'Abandon'],
  ['Settle', 'Make final decision', 'Dispute', 'Argue', 'Contest'],
  ['Shake', 'Move rapidly', 'Still', 'Calm', 'Steady'],
  ['Share', 'Give part to others', 'Keep all', 'Hoard', 'Monopolize'],
  ['Shelter', 'Provide protection', 'Expose', 'Endanger', 'Risk'],
  ['Shield', 'Protect from harm', 'Expose', 'Reveal', 'Uncover'],
  ['Shrink', 'Get smaller', 'Expand', 'Grow', 'Increase'],
  ['Sigh', 'Breathe out heavily', 'Gasp', 'Pant', 'Chuckle'],
  ['Simplify', 'Make easier', 'Complicate', 'Confuse', 'Complexify'],
  ['Skip', 'Jump over', 'Land on', 'Stop at', 'Stay at'],
  ['Slip', 'Lose footing', 'Grip', 'Hold', 'Stand firm'],
  ['Soak', 'Absorb liquid', 'Dry out', 'Dehydrate', 'Drain'],
  ['Solve', 'Find answer to', 'Ignore', 'Avoid', 'Skip'],
  ['Soothe', 'Calm comfortingly', 'Irritate', 'Aggravate', 'Annoy'],
  ['Spark', 'Cause to start', 'Extinguish', 'Put out', 'Stop'],
  ['Spin', 'Turn around fast', 'Stop', 'Freeze', 'Halt'],
  ['Split', 'Divide into parts', 'Join', 'Unite', 'Merge'],
  ['Spoil', 'Ruin something', 'Improve', 'Enhance', 'Better'],
  ['Spread', 'Extend over area', 'Collect', 'Gather', 'Concentrate'],
  ['Squeeze', 'Press tightly', 'Release', 'Loosen', 'Free'],
  ['Stabilize', 'Make steady', 'Destabilize', 'Shake', 'Unsettle'],
  ['Stare', 'Look fixedly at', 'Glance', 'Peek', 'Ignore'],
  ['Starve', 'Suffer from hunger', 'Feast', 'Eat well', 'Thrive'],
  ['Steal', 'Take without permission', 'Give', 'Return', 'Donate'],
  ['Stimulate', 'Excite activity in', 'Depress', 'Calm', 'Sedate'],
  ['Stir', 'Mix by moving', 'Still', 'Settle', 'Calm'],
  ['Stretch', 'Extend body', 'Contract', 'Shrink', 'Fold'],
  ['Strike', 'Hit forcefully', 'Caress', 'Stroke', 'Pat'],
  ['Struggle', 'Fight against', 'Give up', 'Yield', 'Surrender'],
  ['Submit', 'Give in to', 'Resist', 'Fight', 'Defy'],
  ['Succeed', 'Achieve goal', 'Fail', 'Lose', 'Fall short'],
  ['Suffer', 'Experience pain', 'Enjoy', 'Thrive', 'Flourish'],
  ['Suggest', 'Propose idea', 'Order', 'Command', 'Demand'],
  ['Supply', 'Provide needed', 'Deprive', 'Withhold', 'Deny'],
  ['Support', 'Help and back', 'Oppose', 'Fight', 'Undermine'],
  ['Suppose', 'Assume true', 'Know', 'Prove', 'Verify'],
  ['Surrender', 'Give up fighting', 'Fight on', 'Resist', 'Persist'],
  ['Surround', 'Encircle completely', 'Isolate', 'Separate', 'Free'],
  ['Survive', 'Stay alive', 'Die', 'Perish', 'Succumb'],
  ['Suspect', 'Believe guilty', 'Trust', 'Believe in', 'Have faith'],
  ['Suspend', 'Hang from above', 'Support from below', 'Hold up', 'Base'],
  ['Sustain', 'Keep going', 'Stop', 'End', 'Cease'],
  ['Swallow', 'Take in through throat', 'Spit out', 'Reject', 'Expel'],
  ['Swear', 'Promise solemnly', 'Break promise', 'Lie', 'Deceive'],
  ['Sweep', 'Clean with broom', 'Mess up', 'Dirty', 'Litter'],
  ['Symbolize', 'Represent meaning', 'Literally be', 'Actually be', 'Directly mean'],
  ['Sympathize', 'Feel for others', 'Ignore feelings', 'Be indifferent', 'Not care'],
  ['Tackle', 'Deal with problem', 'Avoid', 'Ignore', 'Skip'],
  ['Tame', 'Make less wild', 'Wild', 'Untamed', 'Feral'],
  ['Tap', 'Touch lightly', 'Pound', 'Smash', 'Crush'],
  ['Tempt', 'Entice to do', 'Deter', 'Discourage', 'Warn'],
  ['Tend', 'Care for', 'Neglect', 'Abandon', 'Ignore'],
  ['Terminate', 'End formally', 'Begin', 'Start', 'Initiate'],
  ['Terrify', 'Frighten greatly', 'Comfort', 'Reassure', 'Soothe'],
  ['Testify', 'Give evidence', 'Stay silent', 'Hide truth', 'Conceal'],
  ['Threaten', 'Warn of harm', 'Reassure', 'Comfort', 'Protect'],
  ['Thrill', 'Excite greatly', 'Bore', 'Tire', 'Weary'],
  ['Thrive', 'Grow vigorously', 'Wither', 'Decline', 'Fade'],
  ['Tolerate', 'Accept unwillingly', 'Reject', 'Refuse', 'Ban'],
  ['Torment', 'Cause severe pain', 'Comfort', 'Soothe', 'Relieve'],
  ['Torture', 'Inflict extreme pain', 'Comfort', 'Heal', 'Relieve'],
  ['Trace', 'Follow track of', 'Lose', 'Miss', 'Ignore'],
  ['Trade', 'Exchange goods', 'Keep', 'Hoard', 'Store'],
  ['Transform', 'Change completely', 'Preserve', 'Keep same', 'Maintain'],
  ['Trap', 'Catch in snare', 'Release', 'Free', 'Liberate'],
  ['Treat', 'Deal with medically', 'Neglect', 'Ignore', 'Abandon'],
  ['Tremble', 'Shake with fear', 'Stay calm', 'Be steady', 'Remain still'],
  ['Trick', 'Deceive cleverly', 'Be honest', 'Tell truth', 'Be straight'],
  ['Trigger', 'Cause to happen', 'Prevent', 'Stop', 'Block'],
  ['Triumph', 'Win greatly', 'Lose badly', 'Fail completely', 'Fall'],
  ['Trust', 'Have faith in', 'Doubt', 'Suspect', 'Distrust'],
  ['Twist', 'Turn around itself', 'Straighten', 'Unwind', 'Flatten'],
  ['Uncover', 'Reveal hidden', 'Cover', 'Hide', 'Conceal'],
  ['Undergo', 'Experience something', 'Avoid', 'Skip', 'Escape'],
  ['Undermine', 'Weaken gradually', 'Strengthen', 'Support', 'Reinforce'],
  ['Understand', 'Comprehend', 'Misunderstand', 'Confuse', 'Miss'],
  ['Undertake', 'Take responsibility for', 'Avoid', 'Shirk', 'Dodge'],
  ['Unfold', 'Open up flat', 'Fold', 'Close', 'Wrap'],
  ['Unite', 'Join together', 'Divide', 'Split', 'Separate'],
  ['Unleash', 'Release forcefully', 'Restrain', 'Hold back', 'Contain'],
  ['Unlock', 'Open with key', 'Lock', 'Secure', 'Fasten'],
  ['Unveil', 'Show for first time', 'Hide', 'Cover', 'Conceal'],
  ['Update', 'Make current', 'Keep old', 'Leave outdated', 'Ignore'],
  ['Upgrade', 'Improve version', 'Downgrade', 'Reduce', 'Lower'],
  ['Uphold', 'Support decision', 'Overturn', 'Reverse', 'Undo'],
  ['Upset', 'Make unhappy', 'Please', 'Delight', 'Comfort'],
  ['Urge', 'Strongly encourage', 'Discourage', 'Dissuade', 'Deter'],
  ['Utilize', 'Make use of', 'Waste', 'Ignore', 'Neglect'],
  ['Vanish', 'Disappear completely', 'Appear', 'Emerge', 'Materialize'],
  ['Verify', 'Check truth of', 'Assume', 'Guess', 'Presume'],
  ['Vibrate', 'Shake rapidly', 'Stay still', 'Remain steady', 'Be calm'],
  ['Violate', 'Break rule', 'Follow', 'Obey', 'Comply'],
  ['Visible', 'Able to be seen', 'Invisible', 'Hidden', 'Concealed'],
  ['Volunteer', 'Offer freely', 'Be forced', 'Be compelled', 'Refuse'],
  ['Wander', 'Move aimlessly', 'Stay on path', 'Go directly', 'Follow route'],
  ['Warn', 'Give caution about', 'Encourage', 'Promote', 'Suggest'],
  ['Waste', 'Use carelessly', 'Save', 'Conserve', 'Preserve'],
  ['Wave', 'Move side to side', 'Stay still', 'Freeze', 'Stop'],
  ['Weaken', 'Make less strong', 'Strengthen', 'Fortify', 'Reinforce'],
  ['Whisper', 'Speak very quietly', 'Shout', 'Yell', 'Scream'],
  ['Widen', 'Make broader', 'Narrow', 'Tighten', 'Constrict'],
  ['Witness', 'See happen', 'Miss', 'Overlook', 'Ignore'],
  ['Wonder', 'Be curious about', 'Know', 'Understand', 'Be certain'],
  ['Worship', 'Show deep respect', 'Despise', 'Hate', 'Scorn'],
  ['Wound', 'Injure physically', 'Heal', 'Cure', 'Treat'],
  ['Wrap', 'Cover around', 'Unwrap', 'Open', 'Expose'],
  ['Wreck', 'Destroy badly', 'Build', 'Create', 'Repair'],
  ['Yearn', 'Long deeply for', 'Reject', 'Despise', 'Abhor'],
  ['Yell', 'Shout loudly', 'Whisper', 'Murmur', 'Mumble'],
  ['Yield', 'Give way to', 'Resist', 'Fight', 'Oppose'],
]

function generateBulkQuestions(): QuestionSeed[] {
  const qs: QuestionSeed[] = []

  // Vocabulary from bulk bank
  for (const [word, correct, ...wrongs] of bulkVocabBank) {
    const idx = bulkVocabBank.indexOf([word, correct, ...wrongs])
    const diff = idx < 120 ? 'easy' : idx < 240 ? 'medium' : 'hard'
    const options = shuffleArray([correct, ...wrongs.slice(0, 3)])
    qs.push({
      type: 'vocabulary', difficulty: diff,
      stem: `"${word}" means:`,
      options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
      correct_index: options.indexOf(correct),
      explanation: `"${word}" means "${correct}".`,
      time_limit_ms: 15000, tags: [diff, 'vocabulary'],
    })
  }

  // Generate synonym-type questions from same bank
  for (const [word, correct] of bulkVocabBank) {
    const idx = bulkVocabBank.indexOf([word, correct])
    const diff = idx < 100 ? 'easy' : idx < 200 ? 'medium' : 'hard'
    const distractors = ['Not similar', 'Opposite meaning', `Unrelated to ${word}`, `Completely different from ${word}`]
    const options = shuffleArray([correct, ...distractors.slice(0, 3)])
    if (options.indexOf(correct) >= 0) {
      qs.push({
        type: 'synonym', difficulty: diff,
        stem: `Synonym of "${word}":`,
        options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
        correct_index: options.indexOf(correct),
        explanation: `"${correct}" is a synonym of "${word}".`,
        time_limit_ms: 15000, tags: [diff, 'synonym'],
      })
    }
  }

  return qs
}

function shuffleArray<T>(arr: T[]): T[] {
  const result = [...arr]
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]]
  }
  return result
}

function generateAllQuestions(): QuestionSeed[] {
  const questions: QuestionSeed[] = []

  // -- VOCABULARY --
  for (const [difficulty, entries] of Object.entries(vocabPairs)) {
    for (const [word, correct, ...wrongs] of entries) {
      const options = shuffleArray([correct, ...wrongs.slice(0, 3)])
      questions.push({
        type: 'vocabulary', difficulty,
        stem: `"${word}" means:`,
        options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
        correct_index: options.indexOf(correct),
        explanation: `"${word}" means "${correct}".`,
        time_limit_ms: 15000,
        tags: [difficulty, 'vocabulary'],
      })
    }
  }

  // -- SYNONYM --
  const synDifficulty: Record<number, string> = { 0: 'easy', 1: 'easy' }
  for (const [word, correct, wrong] of synonymPairs) {
    const idx = synonymPairs.indexOf([word, correct, wrong])
    const diff = idx < 35 ? 'easy' : idx < 45 ? 'medium' : 'hard'
    const options = shuffleArray([correct, wrong, `Not ${correct}`, `Opposite of ${correct}`])
    questions.push({
      type: 'synonym', difficulty: diff,
      stem: `Synonym of "${word}":`,
      options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
      correct_index: options.indexOf(correct),
      explanation: `"${correct}" is a synonym of "${word}".`,
      time_limit_ms: 15000,
      tags: [diff, 'synonym'],
    })
  }

  // -- GRAMMAR --
  for (const [difficulty, patterns] of Object.entries(grammarPatterns)) {
    for (const pat of patterns) {
      const options = shuffleArray([pat.answer, ...pat.wrong])
      questions.push({
        type: 'grammar', difficulty,
        stem: pat.stem,
        options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
        correct_index: options.indexOf(pat.answer),
        explanation: `The correct answer is "${pat.answer}".`,
        time_limit_ms: 15000,
        tags: [difficulty, 'grammar'],
      })
    }
  }

  // -- READING --
  for (const [difficulty, passages] of Object.entries(readingPassages)) {
    for (const p of passages) {
      const options = shuffleArray([p.answer, ...p.wrong])
      questions.push({
        type: 'reading', difficulty,
        stem: `${p.passage} What is the answer?`,
        options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
        correct_index: options.indexOf(p.answer),
        explanation: `Based on the passage, the answer is: ${p.answer}.`,
        time_limit_ms: 20000,
        tags: [difficulty, 'reading'],
      })
    }
  }

  // -- TRANSLATION --
  for (const [difficulty, entries] of Object.entries(translations)) {
    for (const [stem, answer, ...wrongs] of entries) {
      const options = shuffleArray([answer, ...wrongs])
      questions.push({
        type: 'translation', difficulty,
        stem,
        options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
        correct_index: options.indexOf(answer),
        explanation: `The correct translation is: ${answer}.`,
        time_limit_ms: 15000,
        tags: [difficulty, 'translation'],
      })
    }
  }

  // -- LISTENING --
  for (const [difficulty, entries] of Object.entries(listeningQuestions)) {
    for (const item of entries) {
      const options = shuffleArray([item.answer, ...item.options.filter(o => o !== item.answer)])
      questions.push({
        type: 'listening', difficulty,
        stem: item.stem,
        options: options.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}`),
        correct_index: options.indexOf(item.answer),
        explanation: `The correct answer is: ${item.answer}.`,
        time_limit_ms: 15000,
        tags: [difficulty, 'listening'],
      })
    }
  }

  // Add bulk-generated questions
  const bulkQs = generateBulkQuestions()
  questions.push(...bulkQs)

  return questions
}

export async function questionRoutes(app: FastifyInstance) {
  app.post('/api/questions/seed', async (_request, reply) => {
    try {
      const questions = generateAllQuestions()
      let count = 0

      for (const q of questions) {
        const { error } = await supabaseAdmin.from('questions').upsert(
          {
            type: q.type,
            difficulty: q.difficulty,
            stem: q.stem,
            options: q.options,
            correct_index: q.correct_index,
            explanation: q.explanation,
            time_limit_ms: q.time_limit_ms,
            tags: q.tags,
          },
          { onConflict: 'stem, type, difficulty' }
        )
        if (!error) count++
      }

      return { success: true, count, total: questions.length }
    } catch (err: any) {
      return reply.status(500).send({ error: err.message })
    }
  })

  // Also support GET for easy browser trigger
  app.get('/api/questions/seed', async (_request, reply) => {
    try {
      const questions = generateAllQuestions()
      let count = 0
      const errors: string[] = []

      for (const q of questions) {
        const { error } = await supabaseAdmin.from('questions').upsert(
          {
            type: q.type,
            difficulty: q.difficulty,
            stem: q.stem,
            options: q.options,
            correct_index: q.correct_index,
            explanation: q.explanation,
            time_limit_ms: q.time_limit_ms,
            tags: q.tags,
          },
          { onConflict: 'stem, type, difficulty' }
        )
        if (!error) count++
        else errors.push(error.message)
      }

      return { success: true, count, total: questions.length, errors: errors.slice(0, 5) }
    } catch (err: any) {
      return reply.status(500).send({ error: err.message })
    }
  })
}
